### ISSUE TITLE
vmware scan failed with go panic

### ISSUE THREAD

**Issue by atomic111** [mondoohq/cnquery#1149]
````cnspec scan vsphere administrator@vsphere.local@192.168.5.24 --ask-pass -f ./mondoo-policy-CIS-VMware-ESXi-7.0-Benchmark---Level-1-\(L1\)---Corporate_Enterprise-Environment-\(general-use\)_2023-04-13_1681376746.yaml 
→ loaded configuration from /home/user/.config/mondoo/mondoo.yml using source default
Enter password:          
→ using service account credentials
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=4

 192.168.5.24 (VMware vCenter Server) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% score: C
 192.168.5.21                         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━─────────  88%
... 2 more assets ...

 1/4 scanned                          ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━─────────────────────────────────────────  47%

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x782f74]

goroutine 230 [running]:
net/http.(*Client).deadline(0xefa1338?)
        /usr/lib/go/src/net/http/client.go:189 +0x14
net/http.(*Client).do(0x0, 0xc002c0b000)
        /usr/lib/go/src/net/http/client.go:600 +0x225
net/http.(*Client).Do(0xef6c0e0?, 0xc00019e0ff?)
        /usr/lib/go/src/net/http/client.go:582 +0x19
go.mondoo.com/ranger-rpc.(*Client).DoClientRequest(0xc002dae640, {0xa802f10?, 0xc00019e000}, {0xa75d180, 0x0}, {0xc0039ea780, 0x25}, {0xa757dc0, 0xc003cbbb60}, {0xa757f40, ...})
        /home/user/go/pkg/mod/go.mondoo.com/ranger-rpc@v0.0.0-20230328135530-12135c17095f/client.go:86 +0x5b4
go.mondoo.com/cnquery/upstream/mvd.(*AdvisoryScannerClient).AnalyseAsset(0xc002dae640, {0xa802f10, 0xc00019e000}, 0xc003cbbb60?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230329161448-226bbec4edb7/upstream/mvd/mvd.ranger.go:54 +0xf7
go.mondoo.com/cnquery/resources/packs/core.(*mqlPlatform).GetVulnerabilityReport(0xc00058e4d0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230329161448-226bbec4edb7/resources/packs/core/platform_advisories.go:134 +0x52f
go.mondoo.com/cnquery/resources/packs/core.(*mqlPlatform).ComputeVulnerabilityReport(0xc002960388)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230329161448-226bbec4edb7/resources/packs/core/core.lr.go:6766 +0x95
go.mondoo.com/cnquery/resources/packs/core.(*mqlPlatform).VulnerabilityReport(0xc002960388)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230329161448-226bbec4edb7/resources/packs/core/core.lr.go:6690 +0x86
go.mondoo.com/cnquery/resources/packs/core.getAdvisoryReport(0xc002573360?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230329161448-226bbec4edb7/resources/packs/core/platform_advisories.go:149 +0x62
go.mondoo.com/cnquery/resources/packs/core.(*mqlPlatformAdvisories).GetList(0xc002960220)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230329161448-226bbec4edb7/resources/packs/core/platform_advisories.go:191 +0x45
go.mondoo.com/cnquery/resources/packs/core.(*mqlPlatformAdvisories).ComputeList(0xc002960220)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230329161448-226bbec4edb7/resources/packs/core/core.lr.go:7338 +0x95
go.mondoo.com/cnquery/resources/packs/core.(*mqlPlatformAdvisories).MqlCompute(0xc00058e460?, {0x972ca24, 0x4})
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230329161448-226bbec4edb7/resources/packs/core/core.lr.go:7298 +0x96
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate(0xc0017c0b80, {0xa809400, 0xc002960220}, {0x972ca24, 0x4}, {0xc00198c540, 0x31}, 0xc0035acfc0)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230329161448-226bbec4edb7/resources/runtime.go:350 +0x3f1
go.mondoo.com/cnquery/llx.runResourceFunction(0xc00058e3f0, 0xc0035aced0, 0xc001bb2e10, 0x100000002)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230329161448-226bbec4edb7/llx/builtin.go:712 +0x22f
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc00058e3f0, 0xc0035aced0, 0xc001bb2e10, 0x10?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230329161448-226bbec4edb7/llx/builtin.go:795 +0xf2
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc00058e3f0, 0xc001bb2e10, 0xc002394510?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230329161448-226bbec4edb7/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc00058e3f0, 0xc0035acdb0?, 0x100000002?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230329161448-226bbec4edb7/llx/llx.go:781 +0x25e
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc001de84d0?, 0xc0035acd80?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230329161448-226bbec4edb7/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc00058e3f0, 0x9736865?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230329161448-226bbec4edb7/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).run(0xc00058e3f0)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230329161448-226bbec4edb7/llx/llx.go:351 +0x2d7
go.mondoo.com/cnquery/llx.(*MQLExecutorV2).Run(0xc001a3cd80?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230329161448-226bbec4edb7/llx/llx.go:283 +0x59
go.mondoo.com/cnspec/policy/executor/internal.(*executionManager).executeCodeBundle(0xc001bb3b30, 0xc001b12960, 0xc0008de108?, {0x0, 0x0})
        /home/user/go/src/go.mondoo.io/cnspec/policy/executor/internal/execution_manager.go:164 +0x517
go.mondoo.com/cnspec/policy/executor/internal.(*executionManager).Start.func1()
        /home/user/go/src/go.mondoo.io/cnspec/policy/executor/internal/execution_manager.go:85 +0x1cb
created by go.mondoo.com/cnspec/policy/executor/internal.(*executionManager).Start
        /home/user/go/src/go.mondoo.io/cnspec/policy/executor/internal/execution_manager.go:54 +0x6a
```

**Comment by atomic111** [comment]
fixed in version 8.5.3
