### ISSUE TITLE
cnquery segfault when running service("<name>").enabled

### ISSUE THREAD

**Issue by scottford-io** [mondoohq/cnquery#1227]
**Describe the bug**
when running `service(<service name>).enabled, cnquery crashes

```
cnspec> service('org.apache.httpd').enabled = false

cnspec> panic: no callback points

goroutine 369 [running]:
go.mondoo.com/cnquery/llx.(*MQLExecutorV2)._newBlockExecutor(0x140003f2620, 0x100000000, 0x14000cb0588, 0x0)
        /home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230516161103-0d8fb28fa904/llx/llx.go:227 +0x6a0
go.mondoo.com/cnquery/llx.NewExecutorV2(0x14001a29e00, 0x14001f92440, 0x14002ba13e0, 0x1400051cd50?)
        /home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230516161103-0d8fb28fa904/llx/llx.go:166 +0x16c
go.mondoo.com/cnquery/mql/internal.(*executionManager).executeCodeBundle(0x14000641b80, 0x140027c0500, 0x112779e00?, {0x0, 0x0})
        /home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230516161103-0d8fb28fa904/mql/internal/execution_manager.go:165 +0x278
go.mondoo.com/cnquery/mql/internal.(*executionManager).Start.func1()
        /home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230516161103-0d8fb28fa904/mql/internal/execution_manager.go:85 +0x15c
created by go.mondoo.com/cnquery/mql/internal.(*executionManager).Start
        /home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230516161103-0d8fb28fa904/mql/internal/execution_manager.go:54 +0x74
```

**To Reproduce**

2. Select '....'
4. Note the error

**Expected behavior**

**Screenshots or CLI Output**
If applicable, add screenshots or the CLI output to help explain your problem.

**Desktop (please complete the following information):**

- OS: [e.g. macOS]
- OS Version: [e.g. 13.0]
- Browser if applicable: [e.g. Chrome, Firefox]
- Browser Version: [e.g. 106]

**Additional context**

**Comment by chris-rock** [comment]
@scottford-io the check should be `service('org.apache.httpd').enabled == false` with `==` instead of one.

We need a way to error here properly, since you cannot assign a value to the resource
