### ISSUE TITLE
go crash if .all with a none exist registrykey resource

### ISSUE THREAD

**Issue by atomic111** [mondoohq/cnquery#1310]
**Describe the bug**
.all produces a go crash if the registry is not existing

```coffee
users.where( sid == /^S-1-5-21-[0-9]+-[0-9]+-[0-9]+-[0-9]{3,}$/ && enabled == true ).where( registrykey( path: 'HKEY_USERS\' + sid).exists ).all( registrykey.property( path: 'HKEY_USERS\' + sid + '\Software\Policies\Microsoft\WindowsMediaPlayer', name: 'PreventCodecDownload' ).value == 1 )
panic: value not computed

goroutine 184 [running]:
go.mondoo.com/cnquery/llx.(*blockExecutor).lookupValue(0xc003725520?, 0xc00287b050?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/data_conversions.go:691 +0x7a
go.mondoo.com/cnquery/llx.(*blockExecutor).lookupValue(0xc0002c33b0, 0xc000298a00?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/data_conversions.go:696 +0x5d
go.mondoo.com/cnquery/llx.(*blockExecutor).resolveRef(0xc000305270?, 0x6?, 0xa?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/data_conversions.go:704 +0x8f
go.mondoo.com/cnquery/llx.(*blockExecutor).resolveValue(0xc00287b050?, 0xc0035d5c00, 0xa87c1c0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/data_conversions.go:723 +0xd7
go.mondoo.com/cnquery/llx.dataOpV2(0x0?, 0xc00287af30, 0xa87c1c0?, 0xb4620f0?, {0xb461368, 0x1}, 0xa87c1b8)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin_simple.go:134 +0x4f
go.mondoo.com/cnquery/llx.stringPlusStringV2(0xffad6b8?, 0x1?, 0xc000305268?, 0x2?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin_simple.go:1745 +0x2d
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc0033fa230, 0xc00287af30, 0xc000b17090, 0x0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:791 +0x119
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc0033fa230, 0xc000b17090, 0x0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc0033fa230, 0xc00287aa50?, 0x500000006?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc003eb1140?, 0x0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc0033fa230, 0xc00287aa20?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).triggerChain(0xc0033fa230, 0xc00287aa20?, 0xc00287af30)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:910 +0x399
go.mondoo.com/cnquery/llx.runResourceFunction.func1({0x8cdb740?, 0xc000e2ae70}, {0x0?, 0x0})
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:740 +0x245
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate(0xc0036d5ec0, {0xb5657c0, 0xc000aea148}, {0xc000304c8c, 0x3}, {0xc003a79d80, 0x32}, 0xc00287ae10)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/resources/runtime.go:365 +0x4dc
go.mondoo.com/cnquery/llx.runResourceFunction(0xc0033fa230, 0xc00287a900, 0xc000b17040, 0x500000005)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:721 +0x22f
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc0033fa230, 0xc00287a900, 0xc000b17040, 0xc002567a78?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:804 +0xf2
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc0033fa230, 0xc000b17040, 0xc0027bf7a0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc0033fa230, 0xc00287aa50?, 0x500000005?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc003eb1140?, 0xc00287aa20?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc0033fa230, 0xa30202c?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).run(0xc0033fa230)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:351 +0x2d7
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunctionBlock(0xc0002c33b0, {0xc003578770, 0x1, 0xc00287a930?}, 0x500000000, 0xc00287a930?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:582 +0x12f
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunctionBlocks(0xc0002c33b0, {0xc000b48588, 0x1, 0x0?}, 0x0?, 0xc0005c3f80?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:553 +0x11b
go.mondoo.com/cnquery/llx.arrayBlockListV2(0xc0002c33b0, 0xc00287a870, 0xc000b16f50, 0x10000000a)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin_array.go:143 +0x5c8
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc0002c33b0, 0xc00287a870, 0xc000b16f50, 0x0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:791 +0x119
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc0002c33b0, 0xc000b16f50, 0x0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc0002c33b0, 0xc000aaf320?, 0x10000000a?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc003725520?, 0x994a740?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc0002c33b0, 0xc000aaf2f0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).triggerChain(0xc0002c33b0, 0xc000aaf2f0?, 0xc00287a870)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:910 +0x399
go.mondoo.com/cnquery/llx.runResourceFunction.func1({0x8b920a0?, 0xc000b48570}, {0x0?, 0x0})
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:740 +0x245
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate(0xc0036d5ec0, {0xb565800, 0xc003578728}, {0xa2f7d33, 0x4}, {0xc003a79c40, 0x31}, 0xc00287a7e0)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/resources/runtime.go:339 +0x37c
go.mondoo.com/cnquery/llx.runResourceFunction(0xc0002c33b0, 0xc00287a780, 0xc000b166e0, 0x100000008)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:721 +0x22f
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc0002c33b0, 0xc00287a780, 0xc000b166e0, 0xc000428488?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:804 +0xf2
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc0002c33b0, 0xc000b166e0, 0x0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc0002c33b0, 0xc000aaf320?, 0x100000008?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc003725520?, 0x13?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc0002c33b0, 0xc000aaf2f0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).triggerChain(0xc0002c33b0, 0xa2fa7b8?, 0xc00287a780)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:910 +0x399
go.mondoo.com/cnquery/llx._resourceWhereV2.func1({0xc003eb0a00?, 0x1, 0xc003242fc0?}, {0x58?, 0x93bbf80?, 0x0?})
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin_resource.go:99 +0x7ec
go.mondoo.com/cnquery/llx.(*arrayBlockCallResults).update(0xc003dbff80, 0x0, 0xc000fb2200)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:488 +0x414
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunctionBlocks.func1(0xc0000b8c00?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:554 +0x27
go.mondoo.com/cnquery/llx.reportSync.func1(0x9089f20?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:370 +0xa2
go.mondoo.com/cnquery/llx.(*blockExecutor).triggerChainError(0xc0033fa000, 0xc000b47f20?, {0xb48e2c0?, 0xc003ddf4f0})
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:931 +0x190
go.mondoo.com/cnquery/llx.runResourceFunction.func1({0x8cdb740?, 0x10588700}, {0xb48e2c0?, 0xc003ddf4f0})
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:737 +0x22d
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate.func1()
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/resources/runtime.go:320 +0x292
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate(0xc0036d5ec0, {0xb567cc0, 0xc0035780d8}, {0xc000304ca4, 0x5}, {0xc003a79bc0, 0x32}, 0xc00287a5a0)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/resources/runtime.go:359 +0x44a
go.mondoo.com/cnquery/llx.runResourceFunction(0xc0033fa000, 0xc00287a540, 0xc000a03ef0, 0x400000007)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:721 +0x22f
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc0033fa000, 0xc00287a540, 0xc000a03ef0, 0x0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:804 +0xf2
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc0033fa000, 0xc000a03ef0, 0x0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc0033fa000, 0xc000b47f50?, 0x400000007?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc003eb0a10?, 0xc000b47f20?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc0033fa000, 0xc000b47f20?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).triggerChain(0xc0033fa000, 0xc000b47f20?, 0xc00287a1b0)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:910 +0x399
go.mondoo.com/cnquery/llx.runResourceFunction.func1({0x8cdb740?, 0xc000e2ae70}, {0x0?, 0x0})
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:740 +0x245
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate(0xc0036d5ec0, {0xb5657c0, 0xc000aea148}, {0xc000304c8c, 0x3}, {0xc003a79b00, 0x32}, 0xc00287a150)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/resources/runtime.go:365 +0x4dc
go.mondoo.com/cnquery/llx.runResourceFunction(0xc0033fa000, 0xc000b47e30, 0xc000a03d10, 0x400000003)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:721 +0x22f
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc0033fa000, 0xc000b47e30, 0xc000a03d10, 0x400000002?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:804 +0xf2
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc0033fa000, 0xc000a03d10, 0xc003eb0a70?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc0033fa000, 0xc000b47f50?, 0x400000003?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc003eb0a10?, 0xc000b47f20?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc0033fa000, 0xa30202c?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).run(0xc0033fa000)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:351 +0x2d7
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunctionBlock(0xc0002c33b0, {0xc003578690, 0x1, 0xc000b4c840?}, 0x400000000, 0xc000b4c840?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:582 +0x12f
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunctionBlocks(0xc0002c33b0, {0xc000b48510, 0x1, 0xa44f1a9?}, 0x0?, 0x0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:553 +0x11b
go.mondoo.com/cnquery/llx._resourceWhereV2(0xc0002c33b0, 0xc000b47c20, 0xc000b16050, 0x100000007, 0x1)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin_resource.go:54 +0x4fd
go.mondoo.com/cnquery/llx.resourceWhereNotV2(0xc000305728?, 0x6?, 0xa309101?, 0x9?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin_resource.go:114 +0x1e
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc0002c33b0, 0xc000b47c20, 0xc000b16050, 0x0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:791 +0x119
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc0002c33b0, 0xc000b16050, 0x0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc0002c33b0, 0xc000aaf320?, 0x100000007?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc003725520?, 0x994a740?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc0002c33b0, 0xc000aaf2f0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).triggerChain(0xc0002c33b0, 0xc000aaf2f0?, 0xc000b47d70)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:910 +0x399
go.mondoo.com/cnquery/llx.runResourceFunction.func1({0x8b920a0?, 0xc000b484f8}, {0x0?, 0x0})
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:740 +0x245
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate(0xc0036d5ec0, {0xb565800, 0xc003578648}, {0xa2f7d33, 0x4}, {0xc003a79ac0, 0x31}, 0xc000b47ce0)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/resources/runtime.go:339 +0x37c
go.mondoo.com/cnquery/llx.runResourceFunction(0xc0002c33b0, 0xc000b47c20, 0xc000b16000, 0x100000006)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:721 +0x22f
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc0002c33b0, 0xc000b47c20, 0xc000b16000, 0x0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:804 +0xf2
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc0002c33b0, 0xc000b16000, 0xc0035a75c8?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc0002c33b0, 0xc000aaf320?, 0x100000006?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc003725520?, 0x13?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc0002c33b0, 0xc000aaf2f0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).triggerChain(0xc0002c33b0, 0xa2fa7b8?, 0xc000b47c20)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:910 +0x399
go.mondoo.com/cnquery/llx._resourceWhereV2.func1({0xc003eb03b0?, 0x1, 0x1?}, {0x0?, 0x0?, 0x0?})
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin_resource.go:99 +0x7ec
go.mondoo.com/cnquery/llx.(*arrayBlockCallResults).update(0xc003dbfdc0, 0x0, 0xc000fb20a0)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:488 +0x414
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunctionBlocks.func1(0xc0000b8c00?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:554 +0x27
go.mondoo.com/cnquery/llx.reportSync.func1(0x9089f20?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:370 +0xa2
go.mondoo.com/cnquery/llx.runResourceFunction.func1({0x8c154c0?, 0xffad688}, {0x0?, 0x0})
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:733 +0x20c
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate.func1()
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/resources/runtime.go:320 +0x292
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate(0xc0036d5ec0, {0xb567c80, 0xc003578528}, {0xc000304c60, 0x6}, {0xc003a79a40, 0x32}, 0xc000b479b0)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/resources/runtime.go:359 +0x44a
go.mondoo.com/cnquery/llx.runResourceFunction(0xc003dbfe30, 0xc000b47950, 0xc000a037c0, 0x300000006)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:721 +0x22f
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc003dbfe30, 0xc000b47950, 0xc000a037c0, 0x0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:804 +0xf2
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc003dbfe30, 0xc000a037c0, 0x40fbaa?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc003dbfe30, 0xc000b47500?, 0x300000006?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc003eb03c0?, 0xc000b474d0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc003dbfe30, 0xc000b474d0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).triggerChain(0xc003dbfe30, 0xc000b474d0?, 0xc000b477a0)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/llx.go:910 +0x399
go.mondoo.com/cnquery/llx.runResourceFunction.func1({0x8cdb740?, 0xc000e2ae70}, {0x0?, 0x0})
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:740 +0x245
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate(0xc0036d5ec0, {0xb5657c0, 0xc000aea148}, {0xc000304c5d, 0x3}, {0xc003a79980, 0x32}, 0xc000b47710)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/resources/runtime.go:365 +0x4dc
go.mondoo.com/cnquery/llx.runResourceFunction(0xc003dbfe30, 0xc000b473e0, 0xc000a03630, 0x300000003)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/llx/builtin.go:721 +0x22f
created by go.mondoo.com/cnquery/mql/internal.(*executionManager).Start
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230619103801-6032fef4d081/mql/internal/execution_manager.go:54 +0x6a
```

**To Reproduce**

1. create a Windows 2019 base VM in AWS
2. cnspec shell ssh Administrator@1.1.1.1 -p 'XXXX'

```coffee
users.where( sid == /^S-1-5-21-[0-9]+-[0-9]+-[0-9]+-[0-9]{3,}$/ && enabled == true ).where( registrykey( path: 'HKEY_USERS\' + sid).exists ).all( registrykey.property( path: 'HKEY_USERS\' + sid + '\Software\Policies\Microsoft\WindowsMediaPlayer', name: 'PreventCodecDownload' ).value == 1 )
panic: value not computed

goroutine 184 [running]:
```

if i write the MQL without .all i get the following correct message:

```coffee
users.where( sid == /^S-1-5-21-[0-9]+-[0-9]+-[0-9]+-[0-9]{3,}$/ && enabled == true ).where( registrykey( path: 'HKEY_USERS\' + sid).exists ) { registrykey.property( path: 'HKEY_USERS\' + sid + '\Software\Policies\Microsoft\WindowsMediaPlayer', name: 'PreventCodecDownload' ).value == 1 }
Query encountered errors:
1 error occurred:
        * requested property does not exist
users.where.where.list: [
  0: {
    registrykey.property.value == 1: requested property does not exist
  }
]
```

**Comment by chris-rock** [comment]
Not reproducable in latest cnquery 10.1.6:

```
cnspec> users.where( sid == /^S-1-5-21-[0-9]+-[0-9]+-[0-9]+-[0-9]{3,}$/ && enabled == true ).where( registrykey( path: 'HKEY_USERS\' + sid).exists ).all( registrykey.property( path: 'HKEY_USERS\' + sid + '\Software\Policies\Microsoft\WindowsMediaPlayer', name: 'PreventCodecDownload' ).value == 1 )
[failed] users.all()
  actual:   [
    0: user uid=-1 name="Administrator" gid=-1 {
      sid: "S-1-5-21-1328968850-797311614-3631678736-500"
    }
  ]

cnspec> 
```

Closing this for now. Please re-open if this problem happens again.
