### ISSUE TITLE
`props.` field in policy will crash cnspec scan

### ISSUE THREAD

**Issue by mm-weber** [mondoohq/cnquery#1352]
## Describe the bug 
- a query will crash cnspec when using `props` with an array in it. (`- uid: cis-01-error-mql-with-props`)
- the same check with an array directly in it will work (`- uid: cis-02-pass-without-props`)

See policy below for examples.

## To Reproduce

Run the policy below with `./cnspec scan aws -f ./example-policy.mql.yaml -o full`

```
policies:
  - uid: props-fail-this-policy
    name: Props Fail This Policy
    version: 1.0.0
    authors:
      - name: Jane Doe
        email: jane@example.com
    groups:
      - filters: asset.platform == "aws"
        checks:
          - uid: cis-01-error-mql-with-props
          - uid: cis-02-pass-without-props
queries:
  - uid: cis-01-error-mql-with-props
    title: Ensure Network Policy is Enabled and set as appropriate
    impact: 70
    props:
      - uid: securityGroupIds
        title: A list of SecurityGroupIds matching the desired network policies (needs to contain at least one value)
        mql: |-
          return
            ["sg-1234567890example","sg-0987654321example"]
    mql: |
      aws.eks.clusters.all(resourcesVpcConfig['SecurityGroupIds'].length != 0 )
      aws.eks.clusters.all(resourcesVpcConfig['SecurityGroupIds'].containsOnly(props.securityGroupIds))
  - uid: cis-02-pass-without-props
    title: Ensure Network Policy is Enabled and set as appropriate
    impact: 70
    mql: |
      aws.eks.clusters.all(resourcesVpcConfig['SecurityGroupIds'].length != 0 )
      aws.eks.clusters.all(resourcesVpcConfig['SecurityGroupIds'].containsOnly(["sg-1234567890example","sg-0987654321example"]))
```

## Expected behavior
The check   `- uid: cis-01-error-mql-with-props)` should work the same as `- uid: cis-02-pass-without-props should`

## Screenshots
![image](https://github.com/mondoohq/cnquery/assets/112621871/7b3c941d-9057-4fed-8f6e-b6613cdc1835)

## CLI Output**
```
→ loaded configuration from /home/manuel/.config/mondoo/mondoo.yml using source $MONDOO_CONFIG_PATH
→ using service account credentials
→ discover related assets for 1 asset(s)
→ no AWS region found, using us-east-1
→ resolved assets resolved-assets=1

 AWS Account lunalectric-edge (247094954579) ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────   0%


panic: value not computed

goroutine 103 [running]:
go.mondoo.com/cnquery/llx.(*blockExecutor).lookupValue(0xc000db5ff0?, 0xc003921f90?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/data_conversions.go:691 +0x7a
go.mondoo.com/cnquery/llx.(*blockExecutor).lookupValue(0xc000df88c0, 0xc0039e1e08?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/data_conversions.go:696 +0x5d
go.mondoo.com/cnquery/llx.(*blockExecutor).resolveRef(0xc0038f04c0?, 0x5?, 0xa?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/data_conversions.go:704 +0x8f
go.mondoo.com/cnquery/llx.(*blockExecutor).resolveValue(0xc000a11d20?, 0xc003891c00, 0xc0039e1fb0?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/data_conversions.go:723 +0xd7
go.mondoo.com/cnquery/llx.arrayDifferenceV2(0xc0038f09c6?, 0xc003b7d560, 0xa38e858?, 0xa?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/builtin_array.go:710 +0xff
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc000df8af0, 0xc003b7d560, 0xc0039201e0, 0xc0039e20d0?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/builtin.go:792 +0x119
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc000df8af0, 0xc0039201e0, 0xc003c843a0?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc000df8af0, 0xc003b7d440?, 0x500000008?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc003c84340?, 0xc003b7d410?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc000df8af0, 0xa37d603?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).run(0xc000df8af0)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:351 +0x2d7
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunctionBlock(0xc000df88c0, {0xc000dae6a0, 0x1, 0xc003b7d320?}, 0x500000000, 0xc003b7d320?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:582 +0x12f
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunctionBlocks(0xc000df88c0, {0xc000db3f98, 0x1, 0xc0039e241c?}, 0xc0039e2520?, 0xc0007ed5c0?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:553 +0x11b
go.mondoo.com/cnquery/llx.arrayBlockListV2(0xc000df88c0, 0xc003b7d260, 0xc0039200a0, 0x10000000a)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/builtin_array.go:143 +0x5c8
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc000df88c0, 0xc003b7d260, 0xc0039200a0, 0x8?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/builtin.go:792 +0x119
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc000df88c0, 0xc0039200a0, 0xc0039e2564?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc000df88c0, 0xc003b7ca80?, 0x10000000a?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc000db5ff0?, 0xc003b7d1d0?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc000df88c0, 0xc003b7ca50?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).triggerChain(0xc000df88c0, 0x1?, 0xc003b7d260)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:910 +0x399
go.mondoo.com/cnquery/llx._arrayWhereV2.func1({0xc003c84140?, 0x1, 0xc0038cd7a0?}, {0x58?, 0xc0038f3450?, 0xc003c842d0?})
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/builtin_array.go:292 +0x2ff
go.mondoo.com/cnquery/llx.(*arrayBlockCallResults).update(0xc000df89a0, 0x0, 0xc003b6c9c0)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:488 +0x414
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunctionBlocks.func1(0x104f9360?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:554 +0x27
go.mondoo.com/cnquery/llx.reportSync.func1(0x90f3040?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:370 +0xa2
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc000df8a10, 0xc003b7ce10?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:852 +0x39f
go.mondoo.com/cnquery/llx.(*blockExecutor).triggerChain(0xc000df8a10, 0xc003b7ce10?, 0xc003b7cfc0)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:910 +0x399
go.mondoo.com/cnquery/llx.runResourceFunction.func1({0x90f0760?, 0xc003a2dd10}, {0x0?, 0x0})
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/builtin.go:741 +0x245
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate(0xc0035e1180, {0x7f3b5841e050, 0xc0005ba3c8}, {0xc003739080, 0x12}, {0xc003b63000, 0x32}, 0xc003b7cf60)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/resources/runtime.go:365 +0x4dc
go.mondoo.com/cnquery/llx.runResourceFunction(0xc000df8a10, 0xc003b7cd20, 0xc0038f3310, 0x300000002)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/builtin.go:722 +0x22f
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc000df8a10, 0xc003b7cd20, 0xc0038f3310, 0xc0039e2e60?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/builtin.go:805 +0xf2
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc000df8a10, 0xc0038f3310, 0xc003b76bd0?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc000df8a10, 0xc003b7ce40?, 0x300000002?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc003c84150?, 0xc0039e3008?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc000df8a10, 0xa37d603?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).run(0xc000df8a10)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:351 +0x2d7
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunctionBlock(0xc000df88c0, {0xc000dae678, 0x1, 0xc000da3f40?}, 0x300000000, 0xc000da3f40?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:582 +0x12f
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunctionBlocks(0xc000df88c0, {0xc000db3ed8, 0x1, 0xc0039e3201?}, 0xc0039e32c8?, 0x64f922e?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:553 +0x11b
go.mondoo.com/cnquery/llx._arrayWhereV2(0xc000df88c0, 0xc003b7cc60, 0xc0038f34a0, 0x100000007, 0x1)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/builtin_array.go:275 +0x4d7
go.mondoo.com/cnquery/llx.arrayWhereNotV2(0xc0000bed50?, 0x11?, 0xa384727?, 0x9?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/builtin_array.go:307 +0x1e
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc000df88c0, 0xc003b7cc60, 0xc0038f34a0, 0xc0039bf4d8?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/builtin.go:792 +0x119
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc000df88c0, 0xc0038f34a0, 0x40fc6a?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc000df88c0, 0xc003b7ca80?, 0x100000007?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc000db5ff0?, 0x99bcc20?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc000df88c0, 0xc003b7ca50?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).triggerChain(0xc000df88c0, 0xc003b7ca50?, 0xc003b7cc60)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:910 +0x399
go.mondoo.com/cnquery/llx.runResourceFunction.func1({0x8bf6260?, 0xc0005c9e60}, {0x0?, 0x0})
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/builtin.go:741 +0x245
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate(0xc0035e1180, {0xb5fa020, 0xc0038b8650}, {0xc0038f01e8, 0x8}, {0xc003b62fc0, 0x31}, 0xc003b7cc00)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/resources/runtime.go:365 +0x4dc
go.mondoo.com/cnquery/llx.runResourceFunction(0xc000df88c0, 0xc003b7cb70, 0xc0038f31d0, 0x100000006)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/builtin.go:722 +0x22f
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc000df88c0, 0xc003b7cb70, 0xc0038f31d0, 0x100000010?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/builtin.go:805 +0xf2
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc000df88c0, 0xc0038f31d0, 0xc003b76990?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc000df88c0, 0xc003b7ca80?, 0x100000006?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc000db5ff0?, 0xc003b7ca50?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc000df88c0, 0xa37d603?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).run(0xc000df88c0)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:351 +0x2d7
go.mondoo.com/cnquery/llx.(*MQLExecutorV2).Run(0xc003912000?)
	/home/manuel/.gvm/pkgsets/go1.20.5/global/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230712142524-fea9630c65b5/llx/llx.go:283 +0x59
go.mondoo.com/cnspec/policy/executor/internal.(*executionManager).executeCodeBundle(0xc0039c4960, 0xc00388ec80, 0xc0038f0210?, {0x0, 0x0})
	/home/manuel/go/src/go.mondoo.io/mondoo/cnspec/policy/executor/internal/execution_manager.go:164 +0x517
go.mondoo.com/cnspec/policy/executor/internal.(*executionManager).Start.func1()
	/home/manuel/go/src/go.mondoo.io/mondoo/cnspec/policy/executor/internal/execution_manager.go:85 +0x1cb
created by go.mondoo.com/cnspec/policy/executor/internal.(*executionManager).Start
	/home/manuel/go/src/go.mondoo.io/mondoo/cnspec/policy/executor/internal/execution_manager.go:54 +0x6a

```

## Version
cnspec 8.18.0 (c76f6a9, 2023-07-11T10:52:06Z)

**Comment by mm-weber** [comment]
This seems solved.

![image](https://github.com/mondoohq/cnquery/assets/112621871/6181b510-d3c3-46de-8fe7-758027de25d1)
