### ISSUE TITLE
cnquery panic when build from latest main - no provider paths exists

### ISSUE THREAD

**Issue by mariuskimmina** [mondoohq/cnquery#1356]
I just rebuild cnquery from the latest main branch and noticed that I now get this error:

```
./cnquery shell
! no provider paths exist home-path=/home/marius/.config/mondoo/providers system-path=/opt/mondoo/providers
panic: INSTALL

goroutine 1 [running]:
go.mondoo.com/cnquery/providers.Install(...)
        /home/marius/projects/mondoo/cnquery/providers/providers.go:163
go.mondoo.com/cnquery/cli/providers.ensureProvider(0xc000040040?, {0x13fed63, 0x5})
        /home/marius/projects/mondoo/cnquery/cli/providers/providers.go:113 +0x197
go.mondoo.com/cnquery/cli/providers.AttachCLIs(0xc00008a6f8?, {0xc00087fee8?, 0x3, 0x3})
        /home/marius/projects/mondoo/cnquery/cli/providers/providers.go:38 +0x89
go.mondoo.com/cnquery/apps/cnquery/cmd.Execute()
        /home/marius/projects/mondoo/cnquery/apps/cnquery/cmd/root.go:47 +0x132
main.main()
        /home/marius/projects/mondoo/cnquery/apps/cnquery/cnquery.go:6 +0x17
```

If I use latest release version 8.18.0 instead I do not get this errors.
I saw that this check has been introduced in ea22978a291c1d851cf55a4e63597109177136f5 but I couldn't find any PR for it. 

Trying to understand why this providers file is now necessary and where should it have come from? Could it be possible for it to keep working as before if the providers file is not present?

**Comment by chris-rock** [comment]
This is expected right now as we re-structure our plug-in system. We recommend using the latest stable releases or sticking with v8 branch until v9 is ready.

**Comment by tas50** [comment]
Reviewed as part of a full backlog triage. This appears resolved in the current codebase:

> providers/providers.go:423 Install and :440 installVersion both return (*Provider, error) with wrapped errors (errors.Wrap); :359 EnsureProvider returns error. Global grep for panic("INSTALL") and 'no provider paths exist' across providers/, cli/, apps/ returns ZERO matches.

The panicking INSTALL flow from the cnquery-era stack trace no longer exists; install path is now fully error-returning. Could equally be marked obsolete (cnquery-era code), but the concern is genuinely gone.

Closing as fixed. If you still see this on a recent release, please reopen with the version.
