### ISSUE TITLE
V9: segfault scanning k8s

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnquery#1749]
**Describe the bug**
```
cnquery scan k8s --log-level trace
DBG using provider k8s with connector k8s
DBG no need to update provider last-refresh=40m34.54718321s provider=k8s
DBG running provider plugin path=/Users/tsmith/.config/mondoo/providers/k8s/k8s
→ loaded configuration from /Users/tsmith/.config/mondoo/mondoo.yml using source default
→ using service account credentials
→ discover related assets for 1 asset(s)
DBG adding 83 discovered asset(s)
DBG running provider plugin path=/Users/tsmith/.config/mondoo/providers/os/os
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x98 pc=0x10146f05c]

goroutine 1 [running]:
go.mondoo.com/cnquery/explorer/scan.(*LocalScanner).distributeJob(0x140008db230, 0x140008b0fc0, {0x1019d14f8, 0x140008db260}, 0x14000752c40)
	/Users/tsmith/dev/cnquery/explorer/scan/local_scanner.go:241 +0x7ac
go.mondoo.com/cnquery/explorer/scan.(*LocalScanner).Run(0x1019d14c0?, {0x1019d14f8?, 0x140008db260?}, 0x10237e7c0?)
	/Users/tsmith/dev/cnquery/explorer/scan/local_scanner.go:92 +0x50
go.mondoo.com/cnquery/apps/cnquery/cmd.RunScan(0x140008df480)
	/Users/tsmith/dev/cnquery/apps/cnquery/cmd/scan.go:287 +0x364
go.mondoo.com/cnquery/apps/cnquery/cmd.glob..func21(0x0?, 0x140002f9b00?, 0x23?)
	/Users/tsmith/dev/cnquery/apps/cnquery/cmd/scan.go:119 +0x94
go.mondoo.com/cnquery/cli/providers.setConnector.func2(0x14000347c00?, {0x14000385ce0?, 0x0, 0x2})
	/Users/tsmith/dev/cnquery/cli/providers/providers.go:336 +0xc8c
github.com/spf13/cobra.(*Command).execute(0x1400039b500, {0x14000385cc0, 0x2, 0x2})
	/Users/tsmith/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x1023334c0)
	/Users/tsmith/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/tsmith/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
go.mondoo.com/cnquery/apps/cnquery/cmd.Execute()
	/Users/tsmith/dev/cnquery/apps/cnquery/cmd/root.go:71 +0x15c
main.main()
	/Users/tsmith/dev/cnquery/apps/cnquery/cnquery.go:9 +0x1c
```

**Comment by czunker** [comment]
I could reproduce this with my local minikube.

**Comment by czunker** [comment]
Ok, the strange thing is, this works when debugging or using builtin, but not with plugins.

This seems related to https://github.com/mondoohq/cnquery/pull/1621/commits/ad6e646bf65041c10d163ab7b6cdcfbb10b60713 and https://github.com/mondoohq/cnquery/pull/1646 where it was solved for `run` and `scan`.

**Comment by czunker** [comment]
The linked PR solves the issue, but I'm not sure whether this breaks other things or I missed something. Need to double-check.
