### ISSUE TITLE
V9: Panic with scan ssh

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnquery#1814]
**Describe the bug**
```
 ~/d/cnquery   *$…  cnquery scan ssh tsmith@nas
→ loaded configuration from /Users/tsmith/.config/mondoo/mondoo.yml using source default
→ using service account credentials
→ discover related assets for 1 asset(s)
! could not find keys in ssh agent
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x100ef50fc]

goroutine 66 [running]:
go.mondoo.com/cnquery/providers/os/connection.(*SshConnection).RunCommand(0x0?, {0x1015143c7?, 0x10194c1e0?})
	/Users/tsmith/dev/cnquery/providers/os/connection/ssh.go:138 +0x1c
go.mondoo.com/cnquery/providers/os/detector.(*OSReleaseDetector).command(0x14000741468?, {0x1015143c7?, 0x14000741488?})
	/Users/tsmith/dev/cnquery/providers/os/detector/os_release.go:27 +0x2c
go.mondoo.com/cnquery/providers/os/detector.(*OSReleaseDetector).unames(...)
	/Users/tsmith/dev/cnquery/providers/os/detector/os_release.go:44
go.mondoo.com/cnquery/providers/os/detector.glob..func36(0x2000?, 0x140000d8540, {0x101c1bc28?, 0x0?})
	/Users/tsmith/dev/cnquery/providers/os/detector/detector_all.go:785 +0x4c
go.mondoo.com/cnquery/providers/os/detector.(*PlatformResolver).resolvePlatform(0x10296aca0, 0x140000d8540, {0x101c1bc28, 0x0})
	/Users/tsmith/dev/cnquery/providers/os/detector/platform_resolver.go:68 +0x38
go.mondoo.com/cnquery/providers/os/detector.(*PlatformResolver).resolvePlatform(0x10296ad20, 0x140000d8540, {0x101c1bc28, 0x0})
	/Users/tsmith/dev/cnquery/providers/os/detector/platform_resolver.go:77 +0xf0
go.mondoo.com/cnquery/providers/os/detector.(*PlatformResolver).resolvePlatform(0x10296ad60, 0x140000d8540, {0x101c1bc28, 0x0})
	/Users/tsmith/dev/cnquery/providers/os/detector/platform_resolver.go:77 +0xf0
go.mondoo.com/cnquery/providers/os/detector.(*PlatformResolver).Resolve(0x14000741718?, {0x101c1bc28?, 0x0?})
	/Users/tsmith/dev/cnquery/providers/os/detector/platform_resolver.go:28 +0x5c
go.mondoo.com/cnquery/providers/os/detector.DetectOS({0x101c1bc28, 0x0})
	/Users/tsmith/dev/cnquery/providers/os/detector/detector.go:18 +0x40
go.mondoo.com/cnquery/providers/os/provider.IdentifyPlatform({0x101c1bc28, 0x0}, 0x140005ec000?, {0x140005ab860, 0x3, 0x3})
	/Users/tsmith/dev/cnquery/providers/os/provider/platform.go:40 +0x3c
go.mondoo.com/cnquery/providers/os/provider.(*Service).connect(0x140006c6bb0, 0x1400009bce0, {0x101c0f4a8?, 0x140005dc9b0})
	/Users/tsmith/dev/cnquery/providers/os/provider/provider.go:303 +0x124
go.mondoo.com/cnquery/providers/os/provider.(*Service).Connect(0x14000117980?, 0x1400009bce0, {0x101c0f4a8?, 0x140005dc9b0?})
	/Users/tsmith/dev/cnquery/providers/os/provider/provider.go:201 +0x38
go.mondoo.com/cnquery/providers-sdk/v1/plugin.(*GRPCServer).Connect(0x14000512820, {0x1400009bce0?, 0x1400014e0e0?}, 0x1400009bce0)
	/Users/tsmith/dev/cnquery/providers-sdk/v1/plugin/grpc.go:92 +0xdc
go.mondoo.com/cnquery/providers-sdk/v1/plugin._ProviderPlugin_Connect_Handler({0x101ab39a0?, 0x14000512820}, {0x101c158f0, 0x140005aa390}, 0x1400014e0e0, 0x0)
	/Users/tsmith/dev/cnquery/providers-sdk/v1/plugin/plugin_grpc.pb.go:179 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000278d20, {0x101c1c998, 0x140006829c0}, 0x1400056c7e0, 0x14000148990, 0x102971e38, 0x0)
	/Users/tsmith/go/pkg/mod/google.golang.org/grpc@v1.58.1/server.go:1376 +0xb44
google.golang.org/grpc.(*Server).handleStream(0x14000278d20, {0x101c1c998, 0x140006829c0}, 0x1400056c7e0, 0x0)
	/Users/tsmith/go/pkg/mod/google.golang.org/grpc@v1.58.1/server.go:1753 +0x7c4
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/Users/tsmith/go/pkg/mod/google.golang.org/grpc@v1.58.1/server.go:998 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 43
	/Users/tsmith/go/pkg/mod/google.golang.org/grpc@v1.58.1/server.go:996 +0x154
x unable to connect to asset error="rpc error: code = Unavailable desc = error reading from server: EOF"
x failed to shutdown the provider error="rpc error: code = Unavailable desc = connection error: desc = \"transport: error while dialing: dial unix /var/folders/5q/75yp5vy56_55pmjdxpcv5mfh0000gn/T/plugin1426113586: connect: connection refused\""
```

This failure is handled in v8:

```
→ loaded configuration from /Users/tsmith/.config/mondoo/mondoo.yml using source default
! no identity file or password are provided for ssh authentication, use either --identity-file, --ask-pass or --password, fall back to ssh agent
→ using service account credentials
→ discover related assets for 1 asset(s)
! could not find keys in ssh agent
→ resolved assets resolved-assets=0
x could not resolve asset error="no authentication method defined" asset=nas
FTL failed to run scan error="failed to resolve multiple assets"
```

**Comment by czunker** [comment]
related to #1812
