### ISSUE TITLE
v9 terraform scans failing

### ISSUE THREAD

**Issue by vjeffrey** [mondoohq/cnquery#1866]
i was trying to do scan compare for terraform, against https://github.com/scottford-io/private-aws-ec2-no-publicIP

everything failed out very quickly

**Comment by czunker** [comment]
I pinged Scott to get access to the repo.

@vjeffrey Do you have some more data what failed?

Basic queries against on of the other repos work:
```
cnquery run terraform /home/christian/workspace/aws-no-publicIP-check/terraform -c "asset{ name title platform ids }"
→ found a new version for 'terraform' provider installed=9.0.1 latest=9.0.2
→ successfully installed terraform provider path=/home/christian/.config/mondoo/providers/terraform version=9.0.2
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
asset: {
  title: "Terraform HCL"
  platform: "terraform-hcl"
  ids: [
    0: "//platformid.api.mondoo.app/runtime/terraform/hash/63d1759f90c65f9da43544d9586fbd6a4a70600db5a9c3194981f0a5cda5f4a9"
  ]
  name: "Terraform Static Analysis directory terraform"
}
```

**Comment by czunker** [comment]
Also, with access to the repo: Basic queries work. I need some more info.

**Comment by vjeffrey** [comment]
`go run apps/cnspec/cnspec.go scan terraform ../private-aws-ec2-no-publicIP -f ../server/policy/bundles-enterprise/terraform-cis-gcp.mql.yaml`

**Comment by vjeffrey** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1032987cc]

goroutine 65 [running]:
go.mondoo.com/cnquery/providers/terraform/resources.initTerraformPlan(0x10349d600?, 0x140002b8240?)
	/home/runner/_work/cnquery/cnquery/providers/terraform/resources/tfplan.go:28 +0x3c
go.mondoo.com/cnquery/providers/terraform/resources.NewResource(0x140003112c0, {0x14000278d70, 0xe}, 0x140002b99b0)
	/home/runner/_work/cnquery/cnquery/providers/terraform/resources/terraform.lr.go:89 +0x84
go.mondoo.com/cnquery/providers/terraform/provider.(*Service).GetData(0x0?, 0x1400023c1c0)
	/home/runner/_work/cnquery/cnquery/providers/terraform/provider/provider.go:180 +0x80
```
