### ISSUE TITLE
cnquery panic: "shell flag redefined: sudo"

### ISSUE THREAD

**Issue by benr** [mondoohq/cnquery#2197]
My laptop automatically (MDM) upgraded to cnquery/cnspec (official Mac PKG installed by Kandji) to 9.1.0.  Running 'cnquery version' paniced if it wasn't run under sudo:

```
lappy:Downloads benr$ tar xfvz cnquery_9.1.0_darwin_amd64.tar.gz
x cnquery
lappy:Downloads benr$ ./cnquery version
panic: shell flag redefined: sudo

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc0001bee00, 0xc0004fcc80)
	/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.6-0.20201009195203-85dd5c8bc61c/flag.go:855 +0x5ec
github.com/spf13/pflag.(*FlagSet).VarPF(0x1f9b4e0?, {0x220c890, 0xc000498e38}, {0xc00032dd58, 0x4}, {0x0, 0x0}, {0xc000495140, 0x1d})
	/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.6-0.20201009195203-85dd5c8bc61c/flag.go:838 +0x14f
github.com/spf13/pflag.(*FlagSet).BoolVarP(0xc000498e30?, 0x5?, {0xc00032dd58?, 0x1d51ea0?}, {0x0?, 0x2059e11?}, 0x33?, {0xc000495140?, 0x2c39140?})
	/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.6-0.20201009195203-85dd5c8bc61c/bool.go:55 +0x3e
github.com/spf13/pflag.(*FlagSet).BoolP(...)
	/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.6-0.20201009195203-85dd5c8bc61c/bool.go:80
github.com/spf13/pflag.(*FlagSet).Bool(...)
	/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.6-0.20201009195203-85dd5c8bc61c/bool.go:74
go.mondoo.com/cnquery/v9/cli/providers.attachFlag(0x0?, {{0xc00032dd58, 0x4}, {0x0, 0x0}, {0xc00032dd60, 0x5}, {0xc000495140, 0x1d}, 0x1, ...})
	/home/runner/_work/cnquery/cnquery/cli/providers/providers.go:272 +0x285
go.mondoo.com/cnquery/v9/cli/providers.attachFlags(...)
	/home/runner/_work/cnquery/cnquery/cli/providers/providers.go:310
go.mondoo.com/cnquery/v9/cli/providers.setConnector(0xc000257680, 0xc0004fcbe0, 0x20a11b0, 0x2bf4200)
	/home/runner/_work/cnquery/cnquery/cli/providers/providers.go:495 +0x345
go.mondoo.com/cnquery/v9/cli/providers.setDefaultConnector(0x1e93c60?, 0xc0004fcbe0, 0xc0004b9f00)
	/home/runner/_work/cnquery/cnquery/cli/providers/providers.go:180 +0xaa
go.mondoo.com/cnquery/v9/cli/providers.attachProvidersToCmd(0xc00014c000?, 0x2?)
	/home/runner/_work/cnquery/cnquery/cli/providers/providers.go:161 +0x22a
go.mondoo.com/cnquery/v9/cli/providers.attachProviders(...)
	/home/runner/_work/cnquery/cnquery/cli/providers/providers.go:133
go.mondoo.com/cnquery/v9/cli/providers.AttachCLIs(0x13?, {0xc0004b9ea8?, 0x3, 0x3})
	/home/runner/_work/cnquery/cnquery/cli/providers/providers.go:48 +0xc8
go.mondoo.com/cnquery/v9/apps/cnquery/cmd.Execute()
	/home/runner/_work/cnquery/cnquery/apps/cnquery/cmd/root.go:48 +0x135
main.main()
	/home/runner/_work/cnquery/cnquery/apps/cnquery/cnquery.go:9 +0xf
	```

I downloaded the Mac binary and experienced the same problem. As seen above.  

I then upgraded Homebrew which installed the Cask (Mac PKG) and then things were fine and I couldn't reproduce the issue.  

When the Mac package is upgraded by Homebrew Cask it will execute an uninstall, deleting /Library/Mondoo, this may have been what resolve the issue by removing the previous providers.

The problem is solved for me now but I'm filing this for posterity.

**Comment by mbainter** [comment]
I ran into the same issue on linux, and deleting the ~/.config/mondoo/providers path also cleared that up for me.

**Comment by chris-rock** [comment]
We improved the provider loading and I could not reproduce it anymore. If this problem happens to come up still with the latest version of cnspec and its providers, please let us know.
