### ISSUE TITLE
panic for ebs snapshot scan

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/cnquery#2344]
**Describe the bug**

```
panic: interface conversion: plugin.Connection is *awsec2ebsconn.AwsEbsConnection, not *connection.AwsConnection

goroutine 56 [running]:
go.mondoo.com/cnquery/v9/providers/aws/resources.(*mqlAwsAccount).id(...)
	/home/runner/_work/cnquery/cnquery/providers/aws/resources/aws_account.go:17
go.mondoo.com/cnquery/v9/providers/aws/resources.createAwsAccount(0x40000f1500, 0x4000452240?)
	/home/runner/_work/cnquery/cnquery/providers/aws/resources/aws.lr.go:6168 +0x1b0
go.mondoo.com/cnquery/v9/providers/aws/resources.NewResource(0x40000f1500, {0x4000108610, 0xb}, 0x40008d7860)
	/home/runner/_work/cnquery/cnquery/providers/aws/resources/aws.lr.go:531 +0xa0
go.mondoo.com/cnquery/v9/providers/aws/provider.(*Service).GetData(0x0?, 0x40007d8540)
	/home/runner/_work/cnquery/cnquery/providers/aws/provider/provider.go:274 +0x80
go.mondoo.com/cnquery/v9/providers-sdk/v1/plugin.(*GRPCServer).GetData(0x5551fc0?, {0x40007d8540?, 0x40007d84d0?}, 0x0?)
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/grpc.go:113 +0x2c
go.mondoo.com/cnquery/v9/providers-sdk/v1/plugin._ProviderPlugin_GetData_Handler({0x53d8540?, 0x40006916a0}, {0x62e9e20, 0x40008d7830}, 0x40007d84d0, 0x0)
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/plugin_grpc.pb.go:233 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x40003acb40, {0x62eecb8, 0x4000483ba0}, 0x40008da5a0, 0x4000452960, 0x83b4b80, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:1374 +0xb44
google.golang.org/grpc.(*Server).handleStream(0x40003acb40, {0x62eecb8, 0x4000483ba0}, 0x40008da5a0, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:1751 +0x7c4
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:986 +0xb4
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 33
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:997 +0x160
```

**To Reproduce**

Run marketplace image

**Expected behavior**

Scans image

**Comment by vjeffrey** [comment]
this appears to be another one of those cases where things work fine with the builtin provider, but when using the installed provider something goes wrong and we end up just in the wrong connection type
