### ISSUE TITLE
:bug: MacOS flaky execution: runtime error: invalid memory address or nil pointer

### ISSUE THREAD

**Issue by mm-weber** [mondoohq/cnquery#2466]
**Describe the bug**
Sometimes when executing
```
cnspec scan -o full 
```

this runs into an error on MacOS 13:
```
mondoo-testing:user root# cnspec scan -o full | grep "Fail:" -A 5
→ no provider specified, defaulting to local. Use --help to see all providers.
→ loaded configuration from /var/root/.config/mondoo/mondoo.yml using source default
→ using service account credentials
→ discover related assets for 1 asset(s)
→ synchronize assets
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x1039be690]

goroutine 4728 [running]:
go.mondoo.com/cnquery/v9/providers/os/resources.(*mqlProcess).MqlID(0x14000715500?)
	/home/runner/_work/cnquery/cnquery/providers/os/resources/os.lr.go:8728
go.mondoo.com/cnquery/v9/llx.resource2result({0x104125080, 0x0}, {0x140005984b8, 0x8})
	/home/runner/_work/cnquery/cnquery/llx/data_conversions.go:319 +0x54
go.mondoo.com/cnquery/v9/llx.raw2primitive({0x104125080, 0x0}, {0x140005984b8, 0x8})
	/home/runner/_work/cnquery/cnquery/llx/data_conversions.go:350 +0x14c
go.mondoo.com/cnquery/v9/llx.(*RawData).Result(0x14000671688)
	/home/runner/_work/cnquery/cnquery/llx/data_conversions.go:375 +0x7c
go.mondoo.com/cnquery/v9/providers-sdk/v1/plugin.(*TValue[...]).ToDataRes(0x103cf07d0?, {0x140005984b8?, 0x103a0aa1b?})
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/runtime.go:185 +0x1b0
go.mondoo.com/cnquery/v9/providers/os/resources.glob..func265({0x1042036f8?, 0x14000c9f680?})
	/home/runner/_work/cnquery/cnquery/providers/os/resources/os.lr.go:1266 +0x74
go.mondoo.com/cnquery/v9/providers/os/resources.GetData({0x1042036f8, 0x14000c9f680}, {0x140005984b0, 0x7}, 0x14000a70fc0?)
	/home/runner/_work/cnquery/cnquery/providers/os/resources/os.lr.go:1906 +0x130
go.mondoo.com/cnquery/v9/providers/os/provider.(*Service).GetData(0x0?, 0x14000a70fc0)
	/home/runner/_work/cnquery/cnquery/providers/os/provider/provider.go:514 +0x304
go.mondoo.com/cnquery/v9/providers-sdk/v1/plugin.(*GRPCServer).GetData(0x1040e7940?, {0x14000a70fc0?, 0x14000d04380?}, 0x0?)
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/grpc.go:121 +0x2c
go.mondoo.com/cnquery/v9/providers-sdk/v1/plugin._ProviderPlugin_GetData_Handler({0x1040a80e0?, 0x1400047f040}, {0x10421bc40, 0x14000d01cb0}, 0x14000d04380, 0x0)
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/plugin_grpc.pb.go:266 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x140001390e0, {0x10421bc40, 0x14000d01c20}, {0x1042236c0, 0x14000682d00}, 0x14000a638c0, 0x140009a5890, 0x10512a198, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1343 +0xb8c
google.golang.org/grpc.(*Server).handleStream(0x140001390e0, {0x1042236c0, 0x14000682d00}, 0x14000a638c0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1737 +0x988
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:986 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 40
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:997 +0x160
```
and
```
Data queries:
platform.eol.date: Never
error: rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /tmp/plugin2911277047: connect: connection refused"
os.hostname: null
```

**To Reproduce**

This just sometimes happens when executing said command on a MacOS13 ARM baremetal machine.

**Expected behavior**
No errors, clean execution

- OS: [e.g. macOS]
```
asset: {
  kind: "baremetal"
  build: "22G91"
  version: "13.5.2"
  title: "macOS, bare metal"
  arch: "arm64"
  ```

```
mondoo-testing:user root# cnspec version
cnspec 9.5.1 (e8298bf, 2023-11-02T10:07:22Z)
```

**Additional context**

**Comment by imilchev** [comment]
@mm-weber have you seen this lately? If not, I would like to close this
