### ISSUE TITLE
Panic caused by shell without terminal interface

### ISSUE THREAD

**Issue by benr** [mondoohq/cnquery#2522]
If you attempt to create a shell without a terminal interface a panic will result.  This is most common if you attempt to start a shell in a container without adding the '-ti' arguments to the run, example:

```
$ docker run -v `pwd`/mondoo-config.yaml:/root/.config/mondoo/mondoo.yml --rm mondoo/cnspec shell
→ no provider specified, defaulting to local.
  Use --help for a list of available providers.
→ loaded configuration from /root/.config/mondoo/mondoo.yml using source default
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=1
panic: inappropriate ioctl for device

goroutine 1 [running]:
go.mondoo.com/cnquery/cli/shell.(*Shell).backupTerminalSettings(...)
        /home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230906161718-58f0545faa25/cli/shell/terminal_posix.go:19
go.mondoo.com/cnquery/cli/shell.(*Shell).RunInteractive(0xc0016913f0, {0x0, 0x0})
        /home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230906161718-58f0545faa25/cli/shell/shell.go:138 +0x952
go.mondoo.com/cnquery/apps/cnquery/cmd.StartShell(0xc00306fe60)
        /home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230906161718-58f0545faa25/apps/cnquery/cmd/shell_run.go:110 +0x9b2
go.mondoo.com/cnspec/apps/cnspec/cmd.glob..func29(0xc00306fe00?, {0x10365fc0?, 0x5b?, 0x0?}, 0x0?, 0x0?)
        /home/runner/_work/cnspec/cnspec/apps/cnspec/cmd/shell.go:269 +0xd2
go.mondoo.com/cnquery/apps/cnquery/cmd/builder.NewProviderCommand.func2(0xc002fd6b00?, {0x10365fc0?, 0x0, 0x0})
        /home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230906161718-58f0545faa25/apps/cnquery/cmd/builder/builder.go:69 +0x124
github.com/spf13/cobra.(*Command).execute(0xc002fdcf00, {0x10365fc0, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x1015a5a0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
go.mondoo.com/cnspec/apps/cnspec/cmd.Execute()
        /home/runner/_work/cnspec/cnspec/apps/cnspec/cmd/root.go:79 +0x1a
main.main()
        /home/runner/_work/cnspec/cnspec/apps/cnspec/cnspec.go:6 +0xf
```

While it's true this is an error on the users part, regardless we should cleanly catch and print an error rather than panic.

**Comment by tas50** [comment]
Reviewed as part of a full backlog triage. This appears resolved in the current codebase:

> cli/shell/program.go:118-122 RunWithCommand() checks `if !isatty.IsTerminal(os.Stdin.Fd()) { return ErrNotTTY }`; ErrNotTTY defined at cli/shell/model.go:29-30. The old terminal_posix.go (backupTerminalSettings/MakeRaw ioctl panic path) no longer exists in cli/shell/. Shell refactored to bubbletea (model.go/program.go).

Non-TTY now returns a clean error instead of panicking on ioctl.

Closing as fixed. If you still see this on a recent release, please reopen with the version.
