### ISSUE TITLE
cnquery SEGFAULT when running asset{*} query

### ISSUE THREAD

**Issue by scottford-io** [mondoohq/cnquery#2724]
**Describe the bug**
Running the query `asset {*}` causes a SEGFAULT in cnquery:

```
cnquery> asset{*}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x100b5b230]

goroutine 42 [running]:
go.mondoo.com/cnquery/v9/providers.(*Runtime).watchAndUpdate(0x14000730460, {0x140007f89a7, 0x5}, {0x0, 0x0}, {0x14000378210, 0x13}, {0x0?, 0x140006b5288?})
	/home/runner/_work/cnquery/cnquery/providers/runtime.go:365 +0x90
go.mondoo.com/cnquery/v9/providers.(*Runtime).WatchAndUpdate(0x1400010c400?, {0x1011d1138, 0x1400010c3c0}, {0x14000378210, 0x13}, {0x1400002fb40, 0x31}, 0x14000664900)
	/home/runner/_work/cnquery/cnquery/providers/runtime.go:345 +0x84
go.mondoo.com/cnquery/v9/llx.runResourceFunction(0x14000502bd0, 0x14000afd080, 0x140012b69b0, 0x20000000f)
	/home/runner/_work/cnquery/cnquery/llx/builtin.go:751 +0x1c8
go.mondoo.com/cnquery/v9/llx.(*blockExecutor).runBoundFunction(0x14000502bd0, 0x14000afd080, 0x140012b69b0, 0x1007b2750?)
	/home/runner/_work/cnquery/cnquery/llx/builtin.go:825 +0xf8
go.mondoo.com/cnquery/v9/llx.(*blockExecutor).runFunction(0x14000502bd0, 0x140012b69b0, 0x1400089a990?)
	/home/runner/_work/cnquery/cnquery/llx/llx.go:810 +0x16c
go.mondoo.com/cnquery/v9/llx.(*blockExecutor).runChunk(0x14000502bd0, 0x14000afd230?, 0x20000000f?)
	/home/runner/_work/cnquery/cnquery/llx/llx.go:827 +0x20c
go.mondoo.com/cnquery/v9/llx.(*blockExecutor).runRef(0x140007b3ec0?, 0x14000afd200?)
	/home/runner/_work/cnquery/cnquery/llx/llx.go:852 +0xfc
go.mondoo.com/cnquery/v9/llx.(*blockExecutor).runChain(0x14000502bd0, 0x100c49a66?)
	/home/runner/_work/cnquery/cnquery/llx/llx.go:884 +0x8c
go.mondoo.com/cnquery/v9/llx.(*blockExecutor).run(0x14000502bd0)
	/home/runner/_work/cnquery/cnquery/llx/llx.go:354 +0x29c
go.mondoo.com/cnquery/v9/llx.(*blockExecutor).runFunctionBlock(0x140001da7e0, {0x140006a6210, 0x1, 0x14000afd110?}, 0x200000000, 0x1400063af30)
	/home/runner/_work/cnquery/cnquery/llx/llx.go:585 +0x194
go.mondoo.com/cnquery/v9/llx.(*blockExecutor).runFunctionBlocks(0x140001da7e0, {0x140006b5820, 0x1, 0x1400061cf60?}, 0x101122ca0?, 0x100429dbc?)
	/home/runner/_work/cnquery/cnquery/llx/llx.go:556 +0x108
go.mondoo.com/cnquery/v9/llx.(*blockExecutor).runBlock(0x140001da7e0, 0x14000afd080, 0x0?, {0x14000072728, 0x0, 0x0?}, 0x100000002)
	/home/runner/_work/cnquery/cnquery/llx/llx.go:620 +0x3a8
go.mondoo.com/cnquery/v9/llx.init.0.func1(0x140007f89c0?, 0x6?, 0x100c4542c?, 0x2?)
	/home/runner/_work/cnquery/cnquery/llx/builtin.go:685 +0x58
go.mondoo.com/cnquery/v9/llx.(*blockExecutor).runBoundFunction(0x140001da7e0, 0x14000afd080, 0x140012b6a00, 0x100046da0?)
	/home/runner/_work/cnquery/cnquery/llx/builtin.go:812 +0x120
go.mondoo.com/cnquery/v9/llx.(*blockExecutor).runFunction(0x140001da7e0, 0x140012b6a00, 0x14000ab61b0?)
	/home/runner/_work/cnquery/cnquery/llx/llx.go:810 +0x16c
go.mondoo.com/cnquery/v9/llx.(*blockExecutor).runChunk(0x140001da7e0, 0x14001289ef0?, 0x100000002?)
	/home/runner/_work/cnquery/cnquery/llx/llx.go:827 +0x20c
go.mondoo.com/cnquery/v9/llx.(*blockExecutor).runRef(0x14000c0ec40?, 0x14001289ec0?)
	/home/runner/_work/cnquery/cnquery/llx/llx.go:852 +0xfc
go.mondoo.com/cnquery/v9/llx.(*blockExecutor).runChain(0x140001da7e0, 0x100c49a66?)
	/home/runner/_work/cnquery/cnquery/llx/llx.go:884 +0x8c
go.mondoo.com/cnquery/v9/llx.(*blockExecutor).run(0x140001da7e0)
	/home/runner/_work/cnquery/cnquery/llx/llx.go:354 +0x29c
go.mondoo.com/cnquery/v9/llx.(*MQLExecutorV2).Run(0x140010dac00?)
	/home/runner/_work/cnquery/cnquery/llx/llx.go:286 +0x64
go.mondoo.com/cnquery/v9/mql/internal.(*executionManager).executeCodeBundle(0x140010db440, 0x14000403f40, 0x30?, {0x0, 0x0})
	/home/runner/_work/cnquery/cnquery/mql/internal/execution_manager.go:169 +0x3e8
go.mondoo.com/cnquery/v9/mql/internal.(*executionManager).Start.func1()
	/home/runner/_work/cnquery/cnquery/mql/internal/execution_manager.go:87 +0x164
created by go.mondoo.com/cnquery/v9/mql/internal.(*executionManager).Start in goroutine 1
	/home/runner/_work/cnquery/cnquery/mql/internal/execution_manager.go:56 +0x70
```

**Comment by arlimus** [comment]
This happens with the `aws` provider

**Comment by vjeffrey** [comment]
interesting, i can't seem to repro this:
```

cnquery> asset { * }
1 error occurred:
	* rpc error: code = Unknown desc = cannot find connection type aws
asset: {
  kind: "api"
  build: ""
  version: ""
  title: "AWS Account"
  arch: ""
  labels: {}
  platform: "aws"
  vulnerabilityReport: rpc error: code = Unknown desc = cannot find connection type aws
  runtime: "aws"
  ids: [
    0: "//platformid.api.mondoo.app/runtime/aws/accounts/921877...
  ]
  name: "AWS Account mondoo-dev (921877...)"
  fqdn: ""
  family: []
}
```
