### ISSUE TITLE
panic: shell flag redefined: sudo

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnquery#2727]
**Describe the bug**
When running `cnquery` and `cnspec` commands on my raspi I get the following failure no matter what command is run:

```
cnquery version
panic: shell flag redefined: sudo

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0x2162d00, 0x2098230)
	/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:848 +0x638
github.com/spf13/pflag.(*FlagSet).VarPF(0x2162d00, {0x1262298, 0x200f858}, {0x200f1c8, 0x4}, {0x0, 0x0}, {0x203e3e0, 0x1d})
	/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:831 +0x148
github.com/spf13/pflag.(*FlagSet).BoolVarP(0x2162d00, 0x200f858, {0x200f1c8, 0x4}, {0x0, 0x0}, 0x0, {0x203e3e0, 0x1d})
	/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.5/bool.go:55 +0x64
github.com/spf13/pflag.(*FlagSet).BoolP(...)
	/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.5/bool.go:80
github.com/spf13/pflag.(*FlagSet).Bool(...)
	/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.5/bool.go:74
go.mondoo.com/cnquery/v9/cli/providers.attachFlag(0x2162d00, {{0x200f1c8, 0x4}, {0x0, 0x0}, {0x200f1d0, 0x5}, {0x203e3e0, 0x1d}, 0x1, ...})
	/home/runner/_work/cnquery/cnquery/cli/providers/providers.go:287 +0x244
go.mondoo.com/cnquery/v9/cli/providers.attachFlags(...)
	/home/runner/_work/cnquery/cnquery/cli/providers/providers.go:325
go.mondoo.com/cnquery/v9/cli/providers.setConnector(0x24bd340, 0x2098190, 0x10f1d58, 0x1b80100)
	/home/runner/_work/cnquery/cnquery/cli/providers/providers.go:512 +0x29c
go.mondoo.com/cnquery/v9/cli/providers.setDefaultConnector(0x24bd340, 0x2098190, 0x251ff14)
	/home/runner/_work/cnquery/cnquery/cli/providers/providers.go:195 +0xcc
go.mondoo.com/cnquery/v9/cli/providers.attachProvidersToCmd(0x20008e0, 0x251ff14)
	/home/runner/_work/cnquery/cnquery/cli/providers/providers.go:176 +0x238
go.mondoo.com/cnquery/v9/cli/providers.attachProviders(...)
	/home/runner/_work/cnquery/cnquery/cli/providers/providers.go:134
go.mondoo.com/cnquery/v9/cli/providers.AttachCLIs(0x1b7fb20, {0x251fee8, 0x4, 0x4})
	/home/runner/_work/cnquery/cnquery/cli/providers/providers.go:49 +0x108
go.mondoo.com/cnquery/v9/apps/cnquery/cmd.BuildRootCmd()
	/home/runner/_work/cnquery/cnquery/apps/cnquery/cmd/root.go:47 +0x1ac
go.mondoo.com/cnquery/v9/apps/cnquery/cmd.Execute()
	/home/runner/_work/cnquery/cnquery/apps/cnquery/cmd/root.go:77 +0x14
main.main()
	/home/runner/_work/cnquery/cnquery/apps/cnquery/cnquery.go:9 +0x14
```

It works fine if you use sudo:

```
sudo cnquery version
cnquery 9.9.4 (cb48efb7, 2023-12-01T10:42:03Z)
```

```
cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

```
cat /proc/cpuinfo
processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 76.80
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 76.80
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 76.80
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 76.80
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: BCM2835
Revision	: a22082
Serial		: 000000000761cf2b
Model		: Raspberry Pi 3 Model B Rev 1.2
```

**Comment by tas50** [comment]
This is fixed in 9.12.1.
