### ISSUE TITLE
Terraform Plan and Terraform State 

### ISSUE THREAD

**Issue by scottford-io** [mondoohq/cnquery#2970]
**Describe the bug**
The `terraform-plan` and `terraform-state` providers crash when trying to run resources in the `terraform-hcl` provider:

### Terraform State Provider running terraform.files resource

```
cnspec> terraform.files
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10168beb0]

goroutine 165 [running]:
github.com/hashicorp/hcl/v2/hclparse.(*Parser).Files(0x14000303498?)
	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.19.1/hclparse/parser.go:137
go.mondoo.com/cnquery/v9/providers/terraform/resources.(*mqlTerraform).files(0x14000178e00)
	/home/runner/_work/cnquery/cnquery/providers/terraform/resources/hcl.go:39 +0x48
go.mondoo.com/cnquery/v9/providers/terraform/resources.(*mqlTerraform).GetFiles.func1()
	/home/runner/_work/cnquery/cnquery/providers/terraform/resources/terraform.lr.go:849 +0x9c
go.mondoo.com/cnquery/v9/providers-sdk/v1/plugin.GetOrCompute[...](0x14000178e48?, 0x14000303758)
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/runtime.go:240 +0x38
go.mondoo.com/cnquery/v9/providers/terraform/resources.(*mqlTerraform).GetFiles(0x140002e4380?)
	/home/runner/_work/cnquery/cnquery/providers/terraform/resources/terraform.lr.go:838 +0x44
go.mondoo.com/cnquery/v9/providers/terraform/resources.glob..func1({0x101cdc4a8?, 0x14000178e00?})
	/home/runner/_work/cnquery/cnquery/providers/terraform/resources/terraform.lr.go:145 +0x38
go.mondoo.com/cnquery/v9/providers/terraform/resources.GetData({0x101cdc4a8, 0x14000178e00}, {0x140004ca4d9, 0x5}, 0x140002e4380?)
	/home/runner/_work/cnquery/cnquery/providers/terraform/resources/terraform.lr.go:389 +0x130
go.mondoo.com/cnquery/v9/providers/terraform/provider.(*Service).GetData(0x0?, 0x140002e4380)
	/home/runner/_work/cnquery/cnquery/providers/terraform/provider/provider.go:252 +0x304
go.mondoo.com/cnquery/v9/providers-sdk/v1/plugin.(*GRPCServer).GetData(0x101c27bc0?, {0x140002e4380?, 0x14000450580?}, 0x0?)
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/grpc.go:121 +0x2c
go.mondoo.com/cnquery/v9/providers-sdk/v1/plugin._ProviderPlugin_GetData_Handler({0x101bfc020?, 0x1400003a620}, {0x101ce4120, 0x1400057a930}, 0x14000450580, 0x0)
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/plugin_grpc.pb.go:266 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000178000, {0x101ce4120, 0x1400057a8a0}, {0x101cea6d0, 0x1400008ab60}, 0x14000001440, 0x1400010bb00, 0x10260d6b8, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.60.1/server.go:1372 +0xb8c
google.golang.org/grpc.(*Server).handleStream(0x14000178000, {0x101cea6d0, 0x1400008ab60}, 0x14000001440)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.60.1/server.go:1783 +0xc44
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.60.1/server.go:1016 +0x5c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 14
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.60.1/server.go:1027 +0x138
```

**To Reproduce**

2. Select '....'
4. Note the error

**Expected behavior**

**Screenshots or CLI Output**
If applicable, add screenshots or the CLI output to help explain your problem.

**Desktop (please complete the following information):**

- OS: [e.g. macOS]
- OS Version: [e.g. 13.0]
- Browser if applicable: [e.g. Chrome, Firefox]
- Browser Version: [e.g. 106]

**Additional context**

**Comment by tas50** [comment]
Reviewed as part of a full backlog triage — **confirmed still open** in the current codebase.

providers/terraform/resources/hcl.go:41 calls conn.Parser().Files() with no nil guard (same unguarded pattern at lines 885, 900). Connection.Parser() returns c.parsed (connection.go:56-57), which is only set in NewHclConnection (hcl_manifest.go:138 parsed: loader.GetParser()); NewPlanConnection (tfplan.go:199-225) and NewStateConnection (tfstate.go:84-110) build the Connection without setting parsed, leaving it nil. So files() still dereferences a nil *hclparse.Parser for plan/state assets.

**Suggested fix approach:** In providers/terraform/resources/hcl.go guard files()/related funcs: if conn.Parser() == nil (i.e. assetType is planfile/statefile) return nil/empty instead of calling .Files(); alternatively initialize an empty hclparse.NewParser() in NewPlanConnection/NewStateConnection in providers/terraform/connection/.
