### ISSUE TITLE
AWS Providers Issue: Insufficient IAM permissions lead to  `goroutine 2811 [running]:`

### ISSUE THREAD

**Issue by mm-weber** [mondoohq/cnquery#3179]
**Describe the bug**

`cnspec scan aws  -f ~/projects/cnspec-enterprise-policies/policies/aws-foundations-benchmark.mql.yaml -o full --verbose --log-level trace` on current `main` `c3e798ba` runs into an error:

```
panic: interface conversion: interface {} is nil, not string

goroutine 2811 [running]:
go.mondoo.com/cnquery/v10/providers/aws/resources.initAwsIamUser(0xc000dce060, 0xc001a5da70)
	/home/runner/_work/cnquery/cnquery/providers/aws/resources/aws_iam.go:724 +0x8d5
go.mondoo.com/cnquery/v10/providers/aws/resources.NewResource(0xc000dce060, {0x662fdd4, 0xc}, 0xc001a5da70)
	/home/runner/_work/cnquery/cnquery/providers/aws/resources/aws.lr.go:654 +0x9a
go.mondoo.com/cnquery/v10/providers/aws/resources.(*mqlAwsIam).virtualMfaDevices(0xc00111a000)
	/home/runner/_work/cnquery/cnquery/providers/aws/resources/aws_iam.go:307 +0x585
go.mondoo.com/cnquery/v10/providers/aws/resources.(*mqlAwsIam).GetVirtualMfaDevices.func1()
	/home/runner/_work/cnquery/cnquery/providers/aws/resources/aws.lr.go:11800 +0x8b
go.mondoo.com/cnquery/v10/providers-sdk/v1/plugin.GetOrCompute[...](0xc00111a180?, 0xc000f33768)
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/runtime.go:240 +0x3a
go.mondoo.com/cnquery/v10/providers/aws/resources.(*mqlAwsIam).GetVirtualMfaDevices(0x407758?)
	/home/runner/_work/cnquery/cnquery/providers/aws/resources/aws.lr.go:11789 +0x3f
go.mondoo.com/cnquery/v10/providers/aws/resources.glob..func247({0x71de1e0?, 0xc00111a000?})
	/home/runner/_work/cnquery/cnquery/providers/aws/resources/aws.lr.go:1448 +0x30
go.mondoo.com/cnquery/v10/providers/aws/resources.GetData({0x71de1e0, 0xc00111a000}, {0xc0011d0600, 0x11}, 0x27?)
	/home/runner/_work/cnquery/cnquery/providers/aws/resources/aws.lr.go:3633 +0x16b
go.mondoo.com/cnquery/v10/providers/aws/provider.(*Service).GetData(0x6368b00?, 0xc000669570)
	/home/runner/_work/cnquery/cnquery/providers/aws/provider/provider.go:317 +0x3ea
go.mondoo.com/cnquery/v10/providers-sdk/v1/plugin.(*GRPCServer).GetData(0x641c440?, {0xc000669570?, 0x4d0446?}, 0x0?)
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/grpc.go:121 +0x1e
go.mondoo.com/cnquery/v10/providers-sdk/v1/plugin._ProviderPlugin_GetData_Handler({0x6368b00?, 0xc000a8a460}, {0x7275178, 0xc001ad0ab0}, 0xc000cb6600, 0x0)
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/plugin_grpc.pb.go:266 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005a0200, {0x7275178, 0xc001ad0a20}, {0x727adc0, 0xc000a13040}, 0xc001b326c0, 0xc000a93590, 0x95e9d38, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.61.0/server.go:1385 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc0005a0200, {0x727adc0, 0xc000a13040}, 0xc001b326c0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.61.0/server.go:1796 +0xfec
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.61.0/server.go:1029 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 53
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.61.0/server.go:1040 +0x135
	```

**To Reproduce**

2. Select '....'
4. Note the error

**Expected behavior**

**Screenshots or CLI Output**
If applicable, add screenshots or the CLI output to help explain your problem.

**Desktop (please complete the following information):**

```
 /home/manuel/projects/cloud-security-testing/aws (manuel/aws/snippets/redshift*)$ cnspec providers

→ builtin (found 2 providers)

  core 10.0.0
  mock 9.0.0 with connectors: mock

→ /home/manuel/.config/mondoo/providers (found 21 providers)

  arista 9.1.17 with connectors: arista
  atlassian 9.1.18 with connectors: atlassian
  aws 10.0.5 with connectors: aws
  azure 10.0.7 with connectors: azure
  equinix 9.1.18 with connectors: equinix
  gcp 10.0.1 with connectors: gcp
  github 10.0.0 with connectors: github
  gitlab 9.1.18 with connectors: gitlab
  google-workspace 9.1.21 with connectors: google-workspace
  ipmi 9.1.18 with connectors: ipmi
  k8s 10.0.2 with connectors: k8s
  ms365 10.0.3 with connectors: ms365
  network 9.1.8 with connectors: host
  oci 10.0.0 with connectors: oci
  okta 10.0.0 with connectors: okta
  opcua 10.0.0 with connectors: opcua
  os 10.0.3 with connectors: local, ssh, winrm, vagrant, container, docker, filesystem
  slack 10.0.0 with connectors: slack
  terraform 9.1.17 with connectors: terraform
  vcd 10.0.0 with connectors: vcd
  vsphere 9.1.18 with connectors: vsphere

→ /opt/mondoo/providers (found 3 providers)

  network 9.1.10 with connectors: host
  os 10.0.1 with connectors: local, ssh, winrm, vagrant, container, docker, filesystem
  vsphere 10.0.1 with connectors: vsphere
```
```
cnspec v10.1.4 (91b8e48, unknown)
```

**Additional context**

**Comment by mm-weber** [comment]
## Reason:
This issues seems to occur when the AWS provider does not have sufficient permissions to access `root` account settings:

The check using `aws.iam.virtualMfaDevices` will fail with an assumed role in one of our testing accounts.

```
cnspec> aws.iam.virtualMfaDevices.none(serialNumber == /arn:aws:iam::.*:mfa\/root-account-mfa-device/)
panic: interface conversion: interface {} is nil, not string

goroutine 105 [running]:
go.mondoo.com/cnquery/v10/providers/aws/resources.initAwsIamUser(0xc000b4cfc0, 0xc000b78f60)
	/home/runner/_work/cnquery/cnquery/providers/aws/resources/aws_iam.go:724 +0x8d5
go.mondoo.com/cnquery/v10/providers/aws/resources.NewResource(0xc000b4cfc0, {0x662fdd4, 0xc}, 0xc000b78f60)
<snipped>
[failed] [].none()
  error: the 'aws' provider crashed: rpc error: code = Unavailable desc = error reading from server: EOF
```

However running it as the `root` user in a different AWS account will successfully return the desired results:

```
cnspec> aws.iam.virtualMfaDevices
aws.iam.virtualMfaDevices: []
cnspec> aws.iam.virtualMfaDevices.none(serialNumber == /arn:aws:iam::.*:mfa\/root-account-mfa-device/)
[ok] value: true
```

**Comment by mm-weber** [comment]
Once one of those checks with insufficient IAM permissions has been executed, the AWS provider doesn't recover.

Here's a test policy with three checks, one of those, will cause the issue described above.
Depending on which check is executed first, potentially all three checks run into the error.

**Comment by mm-weber** [comment]
# Copyright (c) Mondoo, Inc.
# SPDX-License-Identifier: BUSL-1.1

# Read more about the policy structure at https://mondoo.com/docs
policies:
  - uid: sshd-server-policy
    name: SSH Server Policy
    version: 1.0.0
    tags:
      another-key: another-value
      key: value
    authors:
      - name: Jane Doe
        email: jane@example.com
    groups:
      - name: Cloudtrail Variants
        checks:
          - uid: amazon-web-services-foundations--cloudtrail-log-file-validation-enabled
          - uid: amazon-web-services-foundations--default-security-group-vpc-restricts-all-traffic
          - uid: amazon-web-services-foundations--hardware-mfa-enabled-root-user-account
queries:
  - uid: amazon-web-services-foundations--cloudtrail-log-file-validation-enabled
    title: Ensure CloudTrail log file validation is enabled
    impact: 50
    tags:
      cisecurity.org/recommendation: "3.2"
    variants:
      - uid: aws-cloudtrail-log-file-validation-enabled-api
      - uid: aws-cloudtrail-log-file-validation-enabled-single
  - uid: aws-cloudtrail-log-file-validation-enabled-api
    filters: asset.platform == "aws"
    mql: aws.cloudtrail.trails.all(logFileValidationEnabled == true)
  - uid: aws-cloudtrail-log-file-validation-enabled-single
    filters: asset.platform == "aws-cloudtrail-trail"
    mql: aws.cloudtrail.trail.logFileValidationEnabled == true



  - uid: amazon-web-services-foundations--default-security-group-vpc-restricts-all-traffic
    title: Ensure the default security group of every VPC restricts all traffic
    impact: 80
    tags:
      cisecurity.org/recommendation: "5.4"
    variants:
      - uid: aws-vpc-default-security-group-vpc-restricts-all-traffic-api
      - uid: aws-vpc-default-security-group-vpc-restricts-all-traffic-single
      - uid: aws-vpc-default-security-group-vpc-restricts-all-traffic-terraform-hcl
  - uid: aws-vpc-default-security-group-vpc-restricts-all-traffic-api
    filters: asset.platform == "aws"
    mql: |
      aws.ec2.securityGroups.where(name == "default").all(
        ipPermissions.length == 0
      )
      aws.ec2.securityGroups.where(name == "default").all(
        ipPermissionsEgress.length == 0
      )
  - uid: aws-vpc-default-security-group-vpc-restricts-all-traffic-single
    filters: asset.platform == "aws-security-group" && aws.ec2.securitygroup.name == "default"
    mql: |
      aws.ec2.securitygroup.ipPermissions.length == 0
      aws.ec2.securitygroup.ipPermissionsEgress.length == 0
  - uid: aws-vpc-default-security-group-vpc-restricts-all-traffic-terraform-hcl
    filters: |
      asset.platform == 'terraform-hcl'
      terraform.resources.any(nameLabel == 'aws_default_security_group')
    mql: |
      terraform.resources.where(nameLabel == 'aws_default_security_group').all(blocks.none(type == 'ingress'))
      terraform.resources.where(nameLabel == 'aws_default_security_group').all(blocks.none(type == 'egress'))
    docs:
      remediation:
        - id: terraform
          desc: |
            ```
            resource "aws_default_security_group" "default" {
              vpc_id = module.vpc.vpc_id

              #ingress {
              #  protocol  = "-1"
              #  self      = true
              #  from_port = 0
              #  to_port   = 0
              #}

              #egress {
              #  from_port   = 0
              #  to_port     = 0
              #  protocol    = "-1"
              #  cidr_blocks = ["0.0.0.0/0"]
              #}
            }
            ```

  - uid: amazon-web-services-foundations--hardware-mfa-enabled-root-user-account
    title: Ensure hardware MFA is enabled for the 'root' user account
    impact: 80
    filters: asset.platform == "aws"
    tags:
      cisecurity.org/recommendation: "1.6"
    mql: |
      aws.iam.accountSummary.AccountMFAEnabled == 1
      aws.iam.virtualMfaDevices.none(serialNumber == /arn:aws:iam::.*:mfa\/root-account-mfa-device/)

**Comment by mm-weber** [comment]
![image](https://github.com/mondoohq/cnquery/assets/112621871/c47c4f6d-707c-4979-becf-328374c99515)
