### ISSUE TITLE
AWS Provider `panic: runtime error: invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by mm-weber** [mondoohq/cnquery#3374]
**Describe the bug**

Similar to https://github.com/mondoohq/cnquery/issues/3245

Discover the s3-buckets via 
```
cnspec shell aws --discover s3-buckets
```

then run: 
```
aws.cloudtrail.trail.logGroup != empty
```

![image](https://github.com/mondoohq/cnquery/assets/112621871/dd34ab0a-2216-43e3-89b2-4dae7f26d0c2)

**Expected behavior**

**Desktop (please complete the following information):**
```
cnspec v10.4.0 (d59612d, unknown)
cnquery v10.4.0 (b76174696, unknown)
aws 10.2.3 with connectors: aws
```

**Additional context**

**Comment by vjeffrey** [comment]
i'm confused why are we running a cloud trail query on an s3 bucket?

**Comment by HRouhani** [comment]
It seems it works with:
```shell aws --discover cloudtrail-trails```

**Comment by mm-weber** [comment]
Also happens in the context of `cnspec shell aws --discover kms-keys`

```
/home/manuel/projects/cloud-security-testing/aws (manuel/aws/tf/pass-improvements*)$ cnspec shell aws --discover kms-keys
→ loaded configuration from /home/manuel/.config/mondoo/mondoo.yml using source $MONDOO_CONFIG_PATH
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ no AWS region found, using us-east-1
→ selected asset asset=0ad4c87a-6fed-45c8-82ec-e83dcaa16eba selection=1
→ connected to AWS KMS Key
  ___ _ __  ___ _ __   ___  ___ 
 / __| '_ \/ __| '_ \ / _ \/ __|
| (__| | | \__ \ |_) |  __/ (__ 
 \___|_| |_|___/ .__/ \___|\___|
   mondoo™     |_|              
cnspec> aws.kms.key
aws.kms.key: aws.kms.key id="0ad4c87a-6fed-45c8-82ec-e83dcaa16eba" region="us-east-1" metadata.Description="Default key that protects my RDS database volumes when no other key is defined"
cnspec> aws.kms.keys
aws.kms.keys: [
  0: aws.kms.key id="055275fb-c98a-4703-8c67-94fea2b7cd64" region="us-east-1" metadata.Description="mondoo-fail-kms-desc"
  1: aws.kms.key id="0ad4c87a-6fed-45c8-82ec-e83dcaa16eba" region="us-east-1" metadata.Description="Default key that protects my RDS database volumes when no other key is defined"
  2: aws.kms.key id="0d53ffc0-223e-4e75-a6e5-1bee924a54d0" region="us-east-1" metadata.Description="Default key that protects my ACM private keys when no other key is defined"
  3: aws.kms.key id="188ab515-40e1-49ba-9615-52415996124e" region="us-east-1" metadata.Description="A KMS key to encrypt CloudTrail events."
  4: aws.kms.key id="2442b714-b10e-4019-9edb-c70bd634f21a" region="us-east-1" metadata.Description="A KMS key to encrypt CloudTrail events."
  5: aws.kms.key id="2f808ee1-bf52-4a3e-9a15-8b401dd2b65f" region="us-east-1" metadata.Description="Default key that protects my EFS filesystems when no other key is defined"
  6: aws.kms.key id="307623a4-9f4d-44c5-896b-daa982e46816" region="us-east-1" metadata.Description="mondoo-fail-kms-desc"
  7: aws.kms.key id="35aa3458-60b2-4dcf-abd6-09070af06200" region="us-east-1" metadata.Description="A KMS key to encrypt CloudTrail events."
  8: aws.kms.key id="509fc24f-b998-4f6a-bc82-2bfe4c1fc7ee" region="us-east-1" metadata.Description=""
  9: aws.kms.key id="79fb7e37-434b-4dab-93af-2a3a3427b885" region="us-east-1" metadata.Description="mondoo-fail-kms-desc"
  10: aws.kms.key id="81414f05-2357-46ee-88b6-10e8988379a2" region="us-east-1" metadata.Description="A KMS key to encrypt CloudTrail events."
  11: aws.kms.key id="8418108d-c54c-4003-b985-30f83854a0ca" region="us-east-1" metadata.Description="A KMS key to encrypt CloudTrail events."
  12: aws.kms.key id="98fcd1ce-4a8a-4674-bba5-f03ed920671c" region="us-east-1" metadata.Description="Pass KMS Key"
  13: aws.kms.key id="9e01595c-9d65-4736-92d8-bad068ab77b1" region="us-east-1" metadata.Description="mondoo-fail-kms-desc"
  14: aws.kms.key id="a4e78731-3278-48ae-aa3c-900bac1e4238" region="us-east-1" metadata.Description="Default key that protects my EBS volumes when no other key is defined"
  15: aws.kms.key id="a9224be1-9454-4b24-b9bc-39adbf711d1f" region="us-east-1" metadata.Description="Default key that protects my Backup data when no other key is defined"
  16: aws.kms.key id="ace00212-95b3-4897-8097-6be8cb608752" region="us-east-1" metadata.Description="mondoo-fail-kms-desc"
  17: aws.kms.key id="ae1ccf25-181f-48ec-b7cf-6b10e80411a2" region="us-east-1" metadata.Description="A KMS key to encrypt CloudTrail events."
  18: aws.kms.key id="ae2cb84e-c340-4929-ac46-aa51e87d46e5" region="us-east-1" metadata.Description="A KMS key to encrypt CloudTrail events."
  19: aws.kms.key id="b1847216-c37f-473b-8b28-d5ba3cf5fcbe" region="us-east-1" metadata.Description="A KMS key to encrypt CloudTrail events."
  20: aws.kms.key id="cbbacd26-e58b-417a-a0e0-9a5a0d8b84e3" region="us-east-1" metadata.Description="A KMS key to encrypt CloudTrail events."
  21: aws.kms.key id="ce384ef6-2fd9-4e98-befd-37055dee1d20" region="us-east-1" metadata.Description="A KMS key to encrypt CloudTrail events."
  22: aws.kms.key id="d6032a8e-80cd-43b9-b211-d9a46025025b" region="us-east-1" metadata.Description="A KMS key to encrypt CloudTrail events."
  23: aws.kms.key id="d60baada-8c82-49db-801e-2985452539f3" region="us-east-1" metadata.Description="mondoo-fail-kms-desc"
  24: aws.kms.key id="e1d84ae7-1909-4bd8-8730-e623a3d2d0d2" region="us-east-1" metadata.Description="A KMS key to encrypt CloudTrail events."
  25: aws.kms.key id="e3961ca6-37e8-4b23-a181-b05a68fe7978" region="us-east-1" metadata.Description="Pass KMS Key"
  26: aws.kms.key id="e72e32d2-da23-4cd2-bc1c-65c957a516fb" region="us-east-1" metadata.Description="mondoo-fail-kms-desc"
  27: aws.kms.key id="eb0cdd97-c4a6-4da5-a7b6-3d9ed56c39ed" region="us-east-1" metadata.Description="A KMS key to encrypt CloudTrail events."
  28: aws.kms.key id="b1e68e5a-e8cb-4421-9fbf-49e549467c58" region="us-east-2" metadata.Description="Default key that protects my RDS database volumes when no other key is defined"
]
cnspec> aws.cloudtrail.trail.logGroup != empty
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5bc9b20]

goroutine 1263 [running]:
go.mondoo.com/cnquery/v10/providers/aws/resources.(*mqlAwsCloudwatchLoggroup).MqlID(0x9d45930?)
	/home/runner/work/cnquery/cnquery/providers/aws/resources/aws.lr.go:15611
go.mondoo.com/cnquery/v10/llx.resource2result({0x68eb380?, 0x0?}, {0xc000f0b170, 0x18})
	/home/runner/work/cnquery/cnquery/llx/data_conversions.go:321 +0x53
go.mondoo.com/cnquery/v10/llx.raw2primitive({0x68eb380, 0x0}, {0xc000f0b170, 0x18})
	/home/runner/work/cnquery/cnquery/llx/data_conversions.go:352 +0x142
go.mondoo.com/cnquery/v10/llx.(*RawData).Result(0xc000ab9630)
	/home/runner/work/cnquery/cnquery/llx/data_conversions.go:377 +0x77
go.mondoo.com/cnquery/v10/providers-sdk/v1/plugin.(*TValue[...]).ToDataRes(0x7785b38?, {0xc000f0b170?, 0x6ae8602?})
	/home/runner/work/cnquery/cnquery/providers-sdk/v1/plugin/runtime.go:214 +0x1e7
go.mondoo.com/cnquery/v10/providers/aws/resources.init.func1682({0x77b4458?, 0xc000eed688?})
	/home/runner/work/cnquery/cnquery/providers/aws/resources/aws.lr.go:2363 +0x6b
go.mondoo.com/cnquery/v10/providers/aws/resources.GetData({0x77b4458, 0xc000eed688}, {0xc0007635d8, 0x8}, 0x0?)
	/home/runner/work/cnquery/cnquery/providers/aws/resources/aws.lr.go:3642 +0x16b
go.mondoo.com/cnquery/v10/providers-sdk/v1/plugin.(*Service).GetData(0x668e220?, 0xc0006345b0)
	/home/runner/work/cnquery/cnquery/providers-sdk/v1/plugin/service.go:139 +0x323
go.mondoo.com/cnquery/v10/providers-sdk/v1/plugin.(*GRPCServer).GetData(0x9d44e50?, {0x68725a0?, 0xc00169b9a0?}, 0x559de5?)
	/home/runner/work/cnquery/cnquery/providers-sdk/v1/plugin/grpc.go:129 +0x1e
go.mondoo.com/cnquery/v10/providers-sdk/v1/plugin._ProviderPlugin_GetData_Handler({0x68725a0, 0xc000b26c80}, {0x784a938, 0xc0014daea0}, 0xc0016d8700, 0x0)
	/home/runner/work/cnquery/cnquery/providers-sdk/v1/plugin/plugin_grpc.pb.go:299 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000b60400, {0x784a938, 0xc0014dae10}, {0x7851bc0, 0xc000a02000}, 0xc00146e5a0, 0xc00022e7b0, 0x9fcd290, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.61.1/server.go:1385 +0xdd1
google.golang.org/grpc.(*Server).handleStream(0xc000b60400, {0x7851bc0, 0xc000a02000}, 0xc00146e5a0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.61.1/server.go:1796 +0xfb8
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.61.1/server.go:1029 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 36
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.61.1/server.go:1040 +0x125
[failed] aws.cloudtrail.trail.logGroup != <ref>
  error: the 'aws' provider crashed: rpc error: code = Unavailable desc = error reading from server: EOF

cnspec> x plugin process exited error="exit status 2" id=1267858 plugin=/home/manuel/.config/mondoo/providers/aws/aws
```

**Comment by mm-weber** [comment]
Also `cnspec shell aws --discover efs-filesystems`

**Comment by vjeffrey** [comment]
ya the linked pr will fix all these occurrences
