### ISSUE TITLE
Panic in unixps resource on ubios device

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnquery#36]
On my Ubiquiti Ubios system when scanning over ssh I get the following panic:

```
./mondoo scan ssh root@172.16.1.1 --ask-pass --verbose
Enter password:
DBG check if we got the scan config from pipe isNamedPipe=false isTerminal=true size=0
DBG parse url url=ssh://root@172.16.1.1
DBG load ssh identity key=/Users/tsmith/.ssh/id_rsa
DBG load ssh identity key=/Users/tsmith/.ssh/id_ed25519
→ Mondoo 6.14.0-19 (Space: "//captain.api.mondoo.app/spaces/practical-visvesvaraya-957532", Service Account: "2BuCJL2GJxKhS64EdL5T8MN5bMF", Managed Client: "2BuCJOxCitOI8G85nQheCAI5AhK")
→ loaded configuration from /Users/tsmith/.config/mondoo/mondoo.yml using source default
DBG execute policies
DBG local> run command uname -s
DBG local> run command uname -m
DBG local> run command /usr/bin/sw_vers
DBG platform> detected os family=["darwin","bsd","unix","os"] platform=macos
DBG local> run command hostname
DBG local> run command hostname
DBG initialize client authentication issuer=mondoo/ams kid=//agents.api.mondoo.app/spaces/practical-visvesvaraya-957532/serviceaccounts/2BuCJL2GJxKhS64EdL5T8MN5bMF
DBG local> run command hostname
DBG local> run command hostname
DBG successful health check
→ discover related assets for 1 asset(s)
DBG run resolver resolver="Standard Resolver" resolver-id=ssh
DBG establish motor connection
DBG fetch secret from vault secret-id=2EP0kH6c4kZbGqDZ1nJ5WGYtumw vault="In-Memory Vault"
DBG fetch secret from vault secret-id=2EP0kNBTJv1NaHazj7l8nG6Il2i vault="In-Memory Vault"
DBG fetch secret from vault secret-id=2EP0kHiXYkM0U16DsHjm5DwvjjJ vault="In-Memory Vault"
DBG fetch secret from vault secret-id=2EP0kLC5cuYa0WOPoT8qTisVlj3 vault="In-Memory Vault"
DBG connection> load ssh transport
DBG load ssh known_hosts file file=/Users/tsmith/.ssh/known_hosts
DBG enabled ssh password authentication
DBG enabled ssh private key authentication
DBG enabled ssh private key authentication
DBG enabled ssh agent authentication
DBG ssh agent socket found socket=/private/tmp/com.apple.launchd.xa8Bo3TVA8/Listeners
! could not find keys in ssh agent
DBG discovered ssh auth methods methods=2
DBG skip hostkey check the hostkey since the algo is not supported yet
DBG ssh session established host=172.16.1.1 port=22 provider=ssh server=SSH-2.0-dropbear_2018.76
DBG run command command="echo 'hi'" provider=ssh
DBG run command command="uname -s" provider=ssh
DBG run command command="uname -m" provider=ssh
→ use scp instead of sftp
DBG initialized ssh filesystem file-transfer=scpfs
DBG platform> cannot parse lsb config on this linux system error="failed to read scp message header: err=failed to write scp replyOK reply: err=EOF"
DBG run command command="uname -m" provider=ssh
DBG run command command="uname -s" provider=ssh
DBG run command command="test -e /bin/busybox" provider=ssh
DBG run command command="stat -L /bin/busybox --printf '%s\n%f\n%u\n%g\n%X\n%Y\n%C'" provider=ssh
DBG could not parse file stat information path=/bin/busybox
DBG platform> we do not know the linux system, but we do our best in guessing
DBG platform> detected os family=["linux","unix","os"] platform=ubios
DBG run command command=hostname provider=ssh
DBG unable to read /sys/class/dmi/id/product_version error="failed to read scp message header: err=failed to write scp replyOK reply: err=EOF"
DBG unable to read /sys/class/dmi/id/product_name error="failed to read scp message header: err=failed to write scp replyOK reply: err=EOF"
DBG unable to read /sys/class/dmi/id/sys_vendor error="failed to read scp message header: err=failed to write scp replyOK reply: err=EOF"
DBG unable to read /sys/class/dmi/id/bios_vendor error="failed to read scp message header: err=scp: /sys/class/dmi/id/bios_vendor: No such file or directory\n"
DBG detected platform ids id-detector=["transport-platform-id","hostname","cloud-detect"] platform-ids=["//platformid.api.mondoo.app/runtime/ssh/hostkey/SHA256-t+bvFvdw9LEH3T4UFWZ3XJs8/RBn7prLqjUzGl7PLf4","//platformid.api.mondoo.app/hostname/pdx-udm",""]
DBG run command command=hostname provider=ssh
→ resolved assets resolved-assets=1
DBG synchronize asset found=1
→ establish connection to asset pdx-udm (unknown)
DBG establish connection to asset connection=ssh://172.16.1.1 insecure=false
DBG establish motor connection
DBG fetch secret from vault secret-id=2EP0kH6c4kZbGqDZ1nJ5WGYtumw vault="In-Memory Vault"
DBG fetch secret from vault secret-id=2EP0kNBTJv1NaHazj7l8nG6Il2i vault="In-Memory Vault"
DBG fetch secret from vault secret-id=2EP0kHiXYkM0U16DsHjm5DwvjjJ vault="In-Memory Vault"
DBG fetch secret from vault secret-id=2EP0kLC5cuYa0WOPoT8qTisVlj3 vault="In-Memory Vault"
DBG connection> load ssh transport
DBG load ssh known_hosts file file=/Users/tsmith/.ssh/known_hosts
DBG enabled ssh password authentication
DBG enabled ssh private key authentication
DBG enabled ssh private key authentication
DBG enabled ssh agent authentication
DBG ssh agent socket found socket=/private/tmp/com.apple.launchd.xa8Bo3TVA8/Listeners
! could not find keys in ssh agent
DBG discovered ssh auth methods methods=2
DBG skip hostkey check the hostkey since the algo is not supported yet
DBG ssh session established host=172.16.1.1 port=22 provider=ssh server=SSH-2.0-dropbear_2018.76
DBG run command command="echo 'hi'" provider=ssh
DBG established connection
→ run policies for asset asset=pdx-udm
DBG request policies for asset asset=//assets.api.mondoo.app/spaces/practical-visvesvaraya-957532/assets/2EOzIIqaMM7r20kfrACErb2hnja
DBG marketplace> fetch policy bundle from upstream policy=//assets.api.mondoo.app/spaces/practical-visvesvaraya-957532/assets/2EOzIIqaMM7r20kfrACErb2hnja req-id=global
DBG store policy mrn=//policy.api.mondoo.app/policies/kubernetes-apps owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/kubernetes-apps
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-linux-security-baseline owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-linux-security-baseline
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-macos-security-baseline owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-macos-security-baseline
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-windows-security-baseline owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-windows-security-baseline
DBG store policy mrn=//policy.api.mondoo.app/spaces/practical-visvesvaraya-957532/policies/cis-apple-macos-12-0-benchmark-l1 owner=//captain.api.mondoo.app/spaces/practical-visvesvaraya-957532 req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/spaces/practical-visvesvaraya-957532/policies/cis-apple-macos-12-0-benchmark-l1
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-dns-baseline owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-dns-baseline
DBG store policy mrn=//policy.api.mondoo.app/policies/cis-amazon-eks-level-1 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/cis-amazon-eks-level-1
DBG store policy mrn=//policy.api.mondoo.app/policies/platform-eol owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/platform-eol
DBG store policy mrn=//policy.api.mondoo.app/policies/asset-overview owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/asset-overview
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-aws-baseline owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-aws-baseline
DBG store policy mrn=//policy.api.mondoo.app/policies/platform-vulnerability owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/platform-vulnerability
DBG store policy mrn=//policy.api.mondoo.app/policies/cis-kubernetes-level-1 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/cis-kubernetes-level-1
DBG store policy mrn=//captain.api.mondoo.app/spaces/practical-visvesvaraya-957532 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//captain.api.mondoo.app/spaces/practical-visvesvaraya-957532
DBG store policy mrn=//assets.api.mondoo.app/spaces/practical-visvesvaraya-957532/assets/2EOzIIqaMM7r20kfrACErb2hnja owner=//captain.api.mondoo.app/spaces/practical-visvesvaraya-957532 req-id=global uid=
DBG invalidate policy cache policy=//assets.api.mondoo.app/spaces/practical-visvesvaraya-957532/assets/2EOzIIqaMM7r20kfrACErb2hnja
DBG marketplace> fetched policy bundle from upstream policy=//assets.api.mondoo.app/spaces/practical-visvesvaraya-957532/assets/2EOzIIqaMM7r20kfrACErb2hnja req-id=global
DBG client> got policy bundle
DBG client> got policy filters
DBG starting query execution qrid=ZB4B5C2LHO0=
DBG run command command="uname -s" provider=ssh
DBG run command command="uname -m" provider=ssh
→ use scp instead of sftp
DBG initialized ssh filesystem file-transfer=scpfs
DBG platform> cannot parse lsb config on this linux system error="failed to read scp message header: err=scp: /etc/lsb-release: No such file or directory\n"
DBG run command command="uname -m" provider=ssh
DBG run command command="uname -s" provider=ssh
DBG run command command="test -e /bin/busybox" provider=ssh
DBG run command command="stat -L /bin/busybox --printf '%s\n%f\n%u\n%g\n%X\n%Y\n%C'" provider=ssh
DBG could not parse file stat information path=/bin/busybox
DBG platform> we do not know the linux system, but we do our best in guessing
DBG platform> detected os family=["linux","unix","os"] platform=ubios
DBG PT786ExRhZswJLT/7pNdxqUTpBQO8am14XfU5rnWvNXGWCO5qQ4iK9lw8R9Ko4n6lUX4M5nUBtAmAAdWr4qlmg== finished
DBG JYVmcYJg895hFnTpkKUJUTZtfqqeM9yTB4193+q5/oX9WnT0lO7i3BFYDfg9v/uXVI8QTEVgoEJc9xfpp0IrYg== finished
DBG ttv3L9qepQVp0h6DHTu/9VLqjzLkuFgY+3FN/RawopxTjxAVd0zFBECK+U+Te26dmSx0tC5SPIrGYSnnN0R2Gg== finished
DBG K19jsTwWlK1ebD2dwcFAZCRnuwmm4EIqaz2X1ANtBclN3jffWYQf9zwC8sYjaoC+/ikeC0h/M6HRE6NCU7o/uQ== finished
DBG finished query execution qrid=ZB4B5C2LHO0=
DBG TAToVilql1FbQyKohlRbAq5K3BTj1UFi+R4IY1YvGOFApxPO27ogQ6ezgRmFZzzCCIYXSIHboZMK3PPE2FIlHw== finished
DBG starting query execution qrid=9zkS3teYP4Q=
DBG yUHOZ/pJzgQ3FLcnKAPphE4TgWqFptqPWA8GYl4e5Dqg0/YzQWcDml2cbrTEj3nj1rm0azm9povOYMRjTgSvZg== finished
DBG ph+xJ13L9rWnyxqrSjTNUt1C+BJdogBsCwpAYsX2bvfG6HaP1je65obm7jsx3FB/Vn9CTYbi491repoW8B1KNQ== finished
DBG EpnHIF31KeNgY/3Z4KyBuKHQ0kk/i+MyYbTX+ZWiQIAvK6lv4P2Nlf9CKAIrn2KOfCWICteI96BN1e8GA6sNZA== finished
DBG finished query execution qrid=9zkS3teYP4Q=
DBG 0XkZYWgnmPXgpTtYNpzJd3FZ0un8AdahxtbsfudPgM2BqRxjpGfgFv5aHNDxqDB7Es1Ok8xmjsZ7mJYqlw/7zw== finished
DBG starting query execution qrid=FXLvS1MK0FM=
DBG finished query execution qrid=FXLvS1MK0FM=
DBG starting query execution qrid=oTdPQFzPjZM=
DBG finished query execution qrid=oTdPQFzPjZM=
DBG starting query execution qrid=91oXv/HZs98=
DBG 4NypLBgCzGKp8+tbdT/gUJ+DJQnOLUjY5t/l+z7jlUS8qrVz5SKLbSR3MyTZC+D1Kz0qDqRaDmo3O/j6tp9AMQ== finished
DBG JToOi1f+kCtu3UmLVxqCPa1qOtMPOrLeAchLXIxZ7cSOy2JGns9sZNZ3fgN5pXYil2KvjODdHuoM0/I+Aang+g== finished
DBG finished query execution qrid=91oXv/HZs98=
DBG starting query execution qrid=xqECC5zypwY=
DBG finished query execution qrid=xqECC5zypwY=
DBG starting query execution qrid=pWyd4yKxb38=
DBG finished query execution qrid=pWyd4yKxb38=
DBG starting query execution qrid=ZJjc7U9LYqQ=
DBG finished query execution qrid=ZJjc7U9LYqQ=
DBG starting query execution qrid=LYI2Dm4MwkQ=
DBG finished query execution qrid=LYI2Dm4MwkQ=
DBG starting query execution qrid=APkQr5eqclQ=
DBG finished query execution qrid=APkQr5eqclQ=
DBG starting query execution qrid=2ZmNd5/fTAg=
DBG finished query execution qrid=2ZmNd5/fTAg=
DBG starting query execution qrid=NVBCj4YrLuA=
DBG finished query execution qrid=NVBCj4YrLuA=
DBG starting query execution qrid=NjgN0od6gI4=
DBG mCaw5JvXj3A1W+Lk0284EFNBrEp05+Jb2ZSB16BFHGCxuQ0zmwv8RZtF6xUR85tCU76nNboLsymjjkXmBpnXgQ== finished
DBG snnJ3BIhsHaDtAmtuZqvij3C98T7s5Og0EVrzwf0EMNeNPbEEKAVBJ6BHyKeZ+w8dicf88jo6Moo96Uymb/zLg== finished
DBG GDrHxkI7Z9TIsM9EhgzVWfI6mFlkF66kE3ohBEzvdjEuBZMERezzyVW3kDy+WBnra0xifTmDYsOZwMXW8GHtoQ== finished
DBG nt/RGL1ZAuxcExyktmOvkzCyFId991vMfjjk+5xvF3PCMKPSYS6N07y7GV45IEm4XqfAKpY5c/ubPBcDywJ8Xg== finished
DBG 9zjLAQG+sPNAc20wn9CUP8NNth0mOdTSfFS58QSI6pOe4/EjCBDF3SosLEU8BcVud3nEREGZ/HXCuAjLC4U56w== finished
DBG 1l4QRTSN+gDhOdmznR3JZh9GH1a2bx+rjrNHGmhR6d5COB+mGRCIZWhVPG38r7HmHFvrKyM9k5TwJRtDBcWL1g== finished
DBG StH9D0PPjpkoG7QzoGoqCzVlXjsq3gad1UPUZTdHk08Vv4nlxRgixyUSufg6hCdTURfgMB0ucY0x8Vy7bfct/w== finished
DBG ICFoTrO74Kx+rEInrC3/Wwkio9xffoPvHEvah/gJM3DD6GhOLW1OGzDXTKSqO8fLwP2z4Vw3IJVLjRBN2V+nDA== finished
DBG ePxlMbxYHKN1kBQDK8Xokw+BsyY6rBox0oh5qeZ4X9qU4z8wq1pEXTA9ExNoMTKvTA0IKlKMYLDi8z9Oc64sKQ== finished
DBG FVGpJ7glutTEWLQgt6u09EByfph6v+Zy5gGYRiDpjcDFuXQT8g03SZcs0Ogwlh/65ATZq7NVBKnZsEpK++vNuA== finished
DBG 5liZQnwN5ZpXFheZ3xlwiJ7m1s+TaeHIUIbSlfhV6MnEFY5j18RE8GU5pm4/NGbFlWxlM2uG7XQ1KvLrgLu9Bw== finished
DBG EaCUBrr/niA4boc/Vv2vw2IIzvy6CaNxRdDN479isDj0z37YXwgcMbhG+freKAH5Q50oHyUFWPtG93jf96WT1A== finished
DBG nQ1dGapXrASBrPyNTPr01+xXAWsX7wmsN1bAaQduZ17rRiwj29u0oD/fCN0HM4SqBbLyyRuL0RRMXE1wCr0hHA== finished
DBG 13VXYfnMnc74H8XVgiMbH6ZSHxTGQxkhJfUkIiYOBCfUDxHAIJWopMcsea7hXkBTFpbM9lCDnbDBev1z+uagBw== finished
DBG run command command="ps axo pid,pcpu,pmem,vsz,rss,tty,stat,stime,time,uid,command" provider=ssh
DBG finished query execution qrid=NjgN0od6gI4=
panic: runtime error: index out of range [1] with length 0

goroutine 74 [running]:
go.mondoo.com/cnquery/resources/packs/core/processes.ParseLinuxPsResult({0x10cf0cbc0?, 0x14002116f30?})
	/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20220901082621-0cdc2e12c73b/resources/packs/core/processes/unixps.go:57 +0x528
go.mondoo.com/cnquery/resources/packs/core/processes.(*UnixProcessManager).List(0x14000b68ab0)
	/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20220901082621-0cdc2e12c73b/resources/packs/core/processes/unixps.go:153 +0x108
go.mondoo.com/cnquery/resources/packs/core.(*mqlProcesses).GetList(0x14000309c98)
	/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20220901082621-0cdc2e12c73b/resources/packs/core/processes.go:175 +0x58
go.mondoo.com/cnquery/resources/packs/core.(*mqlProcesses).ComputeList(0x14000309c98)
	/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20220901082621-0cdc2e12c73b/resources/packs/core/core.lr.go:8780 +0x4c
go.mondoo.com/cnquery/resources/packs/core.(*mqlProcesses).Compute(0x140011c7a80?, {0x10a6670a9, 0x4})
	/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20220901082621-0cdc2e12c73b/resources/packs/core/core.lr.go:8768 +0x94
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate(0x14001bd36e0, {0x10cfbb0c0, 0x14000309c98}, {0x10a6670a9, 0x4}, {0x140013dcb40, 0x26}, 0x14002116de0)
	/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20220901082621-0cdc2e12c73b/resources/runtime.go:284 +0x2dc
go.mondoo.com/cnquery/llx.runResourceFunctionV1(0x14001c11540, 0x14002116cf0, 0x14001b21ea0, 0x2)
	/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20220901082621-0cdc2e12c73b/llx/builtin_v1.go:691 +0x1d4
go.mondoo.com/cnquery/llx.(*MQLExecutorV1).runBoundFunctionV1(0x14001c11540, 0x14002116cf0, 0x14001b21ea0, 0x4f59ea0?)
	/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20220901082621-0cdc2e12c73b/llx/builtin_v1.go:774 +0xf8
go.mondoo.com/cnquery/llx.(*MQLExecutorV1).runFunction(0x14001c11540, 0x14001b21ea0, 0x125e0a68?)
	/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20220901082621-0cdc2e12c73b/llx/llx_v1.go:469 +0x10c
go.mondoo.com/cnquery/llx.(*MQLExecutorV1).runChunk(0x14001c11540, 0x14001c5fa34?, 0x1c5fa38?)
	/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20220901082621-0cdc2e12c73b/llx/llx_v1.go:486 +0x260
go.mondoo.com/cnquery/llx.(*MQLExecutorV1).runRef(0x14002116030?, 0xbf69700?)
	/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20220901082621-0cdc2e12c73b/llx/llx_v1.go:511 +0xd8
go.mondoo.com/cnquery/llx.(*MQLExecutorV1).runChain(0x14001c11540, 0xa6779da?)
	/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20220901082621-0cdc2e12c73b/llx/llx_v1.go:543 +0xb4
go.mondoo.com/cnquery/llx.(*MQLExecutorV1).Run(0x14001c11540)
	/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20220901082621-0cdc2e12c73b/llx/llx_v1.go:189 +0x1c0
go.mondoo.com/cnquery/llx.RunV1(0x14001fea000?, 0x10a73f8c6?, 0x18?, 0x1400161d6e0?)
	/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20220901082621-0cdc2e12c73b/llx/run_v1.go:15 +0x38
go.mondoo.io/mondoo/policy/executor/internal.(*executionManager).executeCodeBundle(0x14001b82410, 0x14001b28140, 0x14000c57ec8?, {0x0, 0x0})
	/builds/mondoolabs/mondoo/policy/executor/internal/execution_manager.go:177 +0x360
go.mondoo.io/mondoo/policy/executor/internal.(*executionManager).Start.func1()
	/builds/mondoolabs/mondoo/policy/executor/internal/execution_manager.go:87 +0x15c
created by go.mondoo.io/mondoo/policy/executor/internal.(*executionManager).Start
	/builds/mondoolabs/mondoo/policy/executor/internal/execution_manager.go:56 +0x74
```

**Comment by tas50** [comment]
Reviewed as part of a full backlog triage. This appears resolved in the current codebase:

> providers/os/resources/processes/unixps.go:78-81 — ParseLinuxPsResult guards `m := LINUX_PS_REGEX.FindStringSubmatch(line); if len(m) != 12 { return nil, &ErrorParsingPs{Line: line} }` before any m[N] indexing. Call sites at unixps.go:231 and 243 use `entries, err = ParseLinuxPsResult(...)` and propagate err. ErrorParsingPs defined at line 405.

Empty/unmatched ubios ps line now returns an error instead of indexing m[1] on a length-0 slice; the original cnquery panic path is gone.

Closing as fixed. If you still see this on a recent release, please reopen with the version.
