### ISSUE TITLE
os scan error

### ISSUE THREAD

**Issue by vjeffrey** [mondoohq/cnquery#3657]
```
x the 'os' provider crashed: rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /tmp/plugin4175887334: connect: connection refused"

panic: runtime error: index out of range [0] with length 0

goroutine 901 [running]:

go.mondoo.com/cnquery/v10/types.Type.Underlying(...)

/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v10@v10.8.4/types/types.go:190

go.mondoo.com/cnquery/v10/llx.isSuccess({0x1acd900?, 0xc008b84250?}, {0x2561bb8?, 0xc0074f6d7c?})

/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v10@v10.8.4/llx/rawdata.go:360 +0x2a7

go.mondoo.com/cnquery/v10/llx.isSuccess({0x1aa1740, 0xc009030ac8}, {0x2561bb8, 0x1})

/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v10@v10.8.4/llx/rawdata.go:390 +0x25c

go.mondoo.com/cnquery/v10/llx.isSuccess({0x1ddc3e0, 0xc00904d2c0}, {0x2561728, 0x1})

/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v10@v10.8.4/llx/rawdata.go:366 +0x18f

go.mondoo.com/cnquery/v10/llx.(*RawData).IsSuccess(0xc0074f6e28?)

/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v10@v10.8.4/llx/rawdata.go:351 +0x36

go.mondoo.com/cnquery/v10/llx.arrayBlockCallResult.isSuccess({0xc001870000?, 0xc001870030?})

/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v10@v10.8.4/llx/llx.go:448 +0xd4

go.mondoo.com/cnquery/v10/llx.arrayBlockCallResult.toRawData({0xc001870000?, 0xc001870030?})

/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v10@v10.8.4/llx/llx.go:409 +0x27e
```

**Comment by vjeffrey** [comment]
no longer reproducing on main
