### ISSUE TITLE
panic when config is provided but the server is not reachable

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/cnquery#775]
**Describe the bug**

```
cnquery status                                                                                                             x1 5h13m christian/multiprogress[e9863c77]
→ loaded configuration from /Users/chris/go/src/go.mondoo.com/demo.ssh.credentials.json using source $MONDOO_CONFIG_PATH
x could not run api health check error="failed to do request: Post \"http://127.0.0.1:8989/Health/Check\": dial tcp 127.0.0.1:8989: connect: connection refused"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x104889f1c]

goroutine 1 [running]:
go.mondoo.com/ranger-rpc.(*Client).DoClientRequest(0x140001ca100, {0x10c95a370?, 0x140000b80b0}, {0x10c8bdd80, 0x14000da8750}, {0x140006561e0, 0x2b}, {0x10c8b9f20, 0x14000da8780}, {0x10c8b9f40, ...})
	/Users/chris/go/src/go.mondoo.com/workspace/ranger-rpc/client.go:65 +0x2ac
go.mondoo.com/cnquery/upstream.(*AgentManagerClient).PingPong(0x140001ca100, {0x10c95a370, 0x140000b80b0}, 0x14000da8750?)
	/Users/chris/go/src/go.mondoo.com/workspace/cnquery/upstream/upstream.ranger.go:65 +0xc0
go.mondoo.com/cnquery/apps/cnquery/cmd.glob..func26(0x11054c340?, {0x109f38533?, 0x0?, 0x0?})
	/Users/chris/go/src/go.mondoo.com/workspace/cnquery/apps/cnquery/cmd/status.go:99 +0x58c
github.com/spf13/cobra.(*Command).execute(0x11054c340, {0x110744120, 0x0, 0x0})
	/Users/chris/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x11054c060)
	/Users/chris/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/chris/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
go.mondoo.com/cnquery/apps/cnquery/cmd.Execute()
	/Users/chris/go/src/go.mondoo.com/workspace/cnquery/apps/cnquery/cmd/root.go:50 +0x28
main.main()
	/Users/chris/go/src/go.mondoo.com/workspace/cnquery/apps/cnquery/cnquery.go:6 +0x1c
```

the same happens when scan command is used:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x101071f1c]

goroutine 1 [running]:
go.mondoo.com/ranger-rpc.(*Client).DoClientRequest(0x1400190f940, {0x1091423e0?, 0x1400097bfb0}, {0x1090a5d80, 0x140019619b0}, {0x140019633c0, 0x36}, {0x1090a1440, 0x140007313b0}, {0x1090a1460, ...})
	/Users/chris/go/src/go.mondoo.com/workspace/ranger-rpc/client.go:65 +0x2ac
go.mondoo.com/cnquery/explorer.(*QueryConductorClient).SynchronizeAssets(0x1400190f940, {0x1091423e0, 0x1400097bfb0}, 0x3?)
	/Users/chris/go/src/go.mondoo.com/workspace/cnquery/explorer/cnquery_explorer.ranger.go:396 +0xc0
go.mondoo.com/cnquery/explorer/scan.(*LocalScanner).distributeJob(0x1400020e500, 0x14000896fc0, {0x1091423e0?, 0x1400097bfb0}, {{0x0, 0x0}, {0x140015fb840, 0x3e}, {0x140009d9ed8, 0x15}, ...})
	/Users/chris/go/src/go.mondoo.com/workspace/cnquery/explorer/scan/local_scanner.go:151 +0x254
go.mondoo.com/cnquery/explorer/scan.(*LocalScanner).Run(0x1400020e500, {0x1091423e0?, 0x1400097bf50?}, 0x14000896fc0)
	/Users/chris/go/src/go.mondoo.com/workspace/cnquery/explorer/scan/local_scanner.go:89 +0xcc
go.mondoo.com/cnquery/apps/cnquery/cmd.RunScan(0x140015ebc00)
	/Users/chris/go/src/go.mondoo.com/workspace/cnquery/apps/cnquery/cmd/scan.go:495 +0x34c
go.mondoo.com/cnquery/apps/cnquery/cmd.glob..func21(0x0?, {0x10cf2c120?, 0x0?, 0x0?}, 0x0?, 0x0?)
	/Users/chris/go/src/go.mondoo.com/workspace/cnquery/apps/cnquery/cmd/scan.go:317 +0xa8
go.mondoo.com/cnquery/apps/cnquery/cmd/builder.kubernetesProviderCmd.func2(0x14001597200?, {0x10cf2c120?, 0x0?, 0x0?})
	/Users/chris/go/src/go.mondoo.com/workspace/cnquery/apps/cnquery/cmd/builder/builder.go:432 +0x7c
github.com/spf13/cobra.(*Command).execute(0x14001597200, {0x10cf2c120, 0x0, 0x0})
	/Users/chris/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x10cd34060)
	/Users/chris/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/chris/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
go.mondoo.com/cnquery/apps/cnquery/cmd.Execute()
	/Users/chris/go/src/go.mondoo.com/workspace/cnquery/apps/cnquery/cmd/root.go:50 +0x28
main.main()
	/Users/chris/go/src/go.mondoo.com/workspace/cnquery/apps/cnquery/cnquery.go:6 +0x1c
```

**To Reproduce**

1. create a config
2. set invalid upstream server

**Expected behavior**

It should show a proper warning and properly error out

**Screenshots or CLI Output**

see output above

**Desktop (please complete the following information):**

n/a

**Additional context**

**Comment by czunker** [comment]
I cannot reproduce the bug with the default demo config:
```
→ loaded configuration from /tmp/config.yaml using source --config
x could not run api health check error="failed to do request: Post \"http://127.1.1.1:8989/Health/Check\": dial tcp 127.1.1.1:8989: connect: connection refused"
→ Platform:	ubuntu
→ Version:	22.04
→ Hostname:	X1
→ IP:		192.168.1.87
→ Time:		2023-01-16T13:01:49+01:00
→ Version:	unstable (API Version: unstable)
→ API ConnectionConfig:	http://127.1.1.1:8989
→ API Status:	
→ API Time:	
→ API Version:	
! API versions do not match, please update the client
→ Owner:	//captain.api.mondoo.app/spaces/test-infallible-taussig-796596
→ Client:	no managed client
→ Service Account:	//agents.api.mondoo.app/spaces/test-infallible-taussig-796596/serviceaccounts/2KPD90QO2XKZRQqqKRPBMQBUIsE
→ client is registered
x could not connect to Mondoo Platform error="failed to do request: Post \"http://127.1.1.1:8989/AgentManager/PingPong\": dial tcp 127.1.1.1:8989: connect: connection refused"
exit status 1
```

I tried to change the config file and also stopped the server. Both cases didn't show a panic.

**Comment by czunker** [comment]
Scan also does not panic:
```
→ loaded configuration from /tmp/config.yaml using source --config
→ using service account credentials
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=1
→ synchronize assets
FTL failed to run scan error="failed to do request: Post \"http://127.0.0.1:8989/QueryConductor/SynchronizeAssets\": dial tcp 127.0.0.1:8989: connect: connection refused"
```

**Comment by chris-rock** [comment]
Not reproducible on my machine anymore.
