### ISSUE TITLE
panic at wrong input

### ISSUE THREAD

**Issue by preslavgerchev** [mondoohq/cnquery#87]
mistyping a letter can cause the whole cnquery to panic crash, reproduce by:
`cnquery shell local` and then `users(uid:09`, it will immediately panic as we seem to parse input without delay here.

```
cnquery> users(uid: 0panic: Failed to parse integer: strconv.ParseInt: parsing "09": invalid syntax

goroutine 1 [running]:
go.mondoo.com/cnquery/mqlc/parser.(*parser).parseValue(0x14000c3f3c0)
        /Users/preslavgerchev/go/src/go.mondoo.com/cnquery/mqlc/parser/parser.go:319 +0x484
go.mondoo.com/cnquery/mqlc/parser.(*parser).parseOperand(0x14000c3f3c0)
        /Users/preslavgerchev/go/src/go.mondoo.com/cnquery/mqlc/parser/parser.go:474 +0x28
go.mondoo.com/cnquery/mqlc/parser.(*parser).parseExpression(0x14000c3f3c0)
        /Users/preslavgerchev/go/src/go.mondoo.com/cnquery/mqlc/parser/parser.go:823 +0x68
go.mondoo.com/cnquery/mqlc/parser.(*parser).parseArg(0x14000c3f3c0)
        /Users/preslavgerchev/go/src/go.mondoo.com/cnquery/mqlc/parser/parser.go:366 +0x21c
go.mondoo.com/cnquery/mqlc/parser.(*parser).parseOperand(0x14000c3f3c0)
        /Users/preslavgerchev/go/src/go.mondoo.com/cnquery/mqlc/parser/parser.go:553 +0xda8
go.mondoo.com/cnquery/mqlc/parser.(*parser).parseExpression(0x14000c3f3c0)
        /Users/preslavgerchev/go/src/go.mondoo.com/cnquery/mqlc/parser/parser.go:823 +0x68
go.mondoo.com/cnquery/mqlc/parser.Parse({0x14000377cd0, 0xd})
        /Users/preslavgerchev/go/src/go.mondoo.com/cnquery/mqlc/parser/parser.go:873 +0x16c
go.mondoo.com/cnquery/mqlc.compile({0x14000377cd0?, 0x2?}, 0x2?, 0x14000c3f402?)
        /Users/preslavgerchev/go/src/go.mondoo.com/cnquery/mqlc/mqlc.go:1521 +0x34
go.mondoo.com/cnquery/mqlc.Compile({0x14000377cd0, 0xd}, 0xd?, {0x10f352d18?, 0x7200000065?, 0x2800000073?}, 0x6900000075?)
        /Users/preslavgerchev/go/src/go.mondoo.com/cnquery/mqlc/mqlc.go:1558 +0x64
go.mondoo.com/cnquery/cli/shell.(*Completer).CompletePrompt(0x14000350c60, {{0x14000377cc0, 0xd}, 0xd, 0x56})
        /Users/preslavgerchev/go/src/go.mondoo.com/cnquery/cli/shell/completer.go:40 +0x100
github.com/c-bata/go-prompt.(*CompletionManager).Update(...)
        /Users/preslavgerchev/go/pkg/mod/github.com/c-bata/go-prompt@v0.2.6/completion.go:68
github.com/c-bata/go-prompt.(*Prompt).Run(0x140012e8000)
        /Users/preslavgerchev/go/pkg/mod/github.com/c-bata/go-prompt@v0.2.6/prompt.go:99 +0x590
go.mondoo.com/cnquery/cli/shell.(*Shell).RunInteractive(0x140012c8000, {0x0, 0x0})
        /Users/preslavgerchev/go/src/go.mondoo.com/cnquery/cli/shell/shell.go:190 +0x780
go.mondoo.com/cnquery/apps/cnquery/cmd.StartShell(0x140009c2cc0)
        /Users/preslavgerchev/go/src/go.mondoo.com/cnquery/apps/cnquery/cmd/shell_run.go:95 +0x5e4
go.mondoo.com/cnquery/apps/cnquery/cmd.glob..func8(0x0?, {0x10f7e8950?, 0x0?, 0x0?}, 0x0?, 0x0?)
        /Users/preslavgerchev/go/src/go.mondoo.com/cnquery/apps/cnquery/cmd/shell.go:230 +0x64
go.mondoo.com/cnquery/apps/cnquery/cmd/builder.localProviderCmd.func1(0x14001121400?, {0x10f7e8950?, 0x0?, 0x0?})
        /Users/preslavgerchev/go/src/go.mondoo.com/cnquery/apps/cnquery/cmd/builder/builder.go:186 +0x30
github.com/spf13/cobra.(*Command).execute(0x14001121400, {0x10f7e8950, 0x0, 0x0})
        /Users/preslavgerchev/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x4b8
github.com/spf13/cobra.(*Command).ExecuteC(0x10f5f5880)
        /Users/preslavgerchev/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/preslavgerchev/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
go.mondoo.com/cnquery/apps/cnquery/cmd.Execute()
        /Users/preslavgerchev/go/src/go.mondoo.com/cnquery/apps/cnquery/cmd/root.go:39 +0x28
main.main()
        /Users/preslavgerchev/go/src/go.mondoo.com/cnquery/apps/cnquery/cnquery.go:6 +0x1c
```

i think we can make this a bit more friendlier to not crash (or delay input parsing somehow?)

to clarify the crash: the 0 in the front means cnquery expects an octal input and 9 is not an octal valid digit, hence the crash

**Comment by tas50** [comment]
This no longer panics. It just throws a compilation error
